namespace Pegasus.Infrastructure.Intake.DocumentExtraction.Cfb;

internal enum CompoundFileReadError
{
    Uninitialized = 0,
    None,
    InputLimitExceeded,
    HeaderInvalid,
    SectorCountLimitExceeded,
    SectorOutOfRange,
    InvalidDifat,
    DifatCycle,
    InvalidFat,
    FatCycle,
    SectorCrossLinked,
    InvalidMiniFat,
    MiniFatCycle,
    InvalidDirectoryChain,
    DirectoryEntryLimitExceeded,
    InvalidDirectoryEntry,
    InvalidDirectoryTree,
    DirectoryTreeCycle,
    DirectoryEntryCrossLinked,
    StreamLimitExceeded,
    TotalStreamLimitExceeded,
    StreamChainLengthMismatch,
    UnallocatedSectorReferenced,
    AllocatedSectorUnreferenced,
    Cancelled,
}
