// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Pegasus.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class WorkflowTriageEmailEvidence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var isSqlite = ActiveProvider == "Microsoft.EntityFrameworkCore.Sqlite";
            string SqlType(string sqlServerType) => isSqlite
                ? sqlServerType switch
                {
                    "bigint" or "bit" or "int" => "INTEGER",
                    "datetime2" or "datetimeoffset" or "uniqueidentifier" => "TEXT",
                    "rowversion" => "BLOB",
                    _ when sqlServerType.StartsWith("nchar", StringComparison.Ordinal)
                        || sqlServerType.StartsWith("nvarchar", StringComparison.Ordinal) => "TEXT",
                    _ => throw new InvalidOperationException($"Unsupported SQLite column type mapping for '{sqlServerType}'.")
                }
                : sqlServerType;

            migrationBuilder.CreateTable(
                name: "ActionHistory",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    AggregateType = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    AggregateId = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    EventKind = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    ActorKind = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: false),
                    ActorSubjectId = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    ActorRolesJson = table.Column<string>(type: "TEXT", nullable: false),
                    OccurredAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false),
                    Outcome = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: false),
                    CorrelationId = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    Reason = table.Column<string>(type: SqlType("nvarchar(1000)"), maxLength: 1000, nullable: true),
                    BeforeJson = table.Column<string>(type: "TEXT", nullable: true),
                    AfterJson = table.Column<string>(type: "TEXT", nullable: true),
                    PolicyVersion = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ActionHistory", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SecurityEvents",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    Type = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: false),
                    Outcome = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: false),
                    SubjectId = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    OccurredAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false),
                    CorrelationId = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    ReasonCode = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SecurityEvents", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Triage",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    OriginReceiptId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    SourceChannel = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: false),
                    ExternalReceiptToken = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    SourceHash = table.Column<string>(type: SqlType("nchar(64)"), fixedLength: true, maxLength: 64, nullable: false),
                    EvaluationRevisionId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    NormalizedVehicleRegistration = table.Column<string>(type: SqlType("nvarchar(20)"), maxLength: 20, nullable: false),
                    State = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: false),
                    AssigneeId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: true),
                    LinkedCaseId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: true),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false),
                    CreationOperationKey = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    Version = table.Column<long>(type: SqlType("bigint"), nullable: false),
                    RowVersion = table.Column<byte[]>(type: SqlType("rowversion"), rowVersion: true, nullable: false),
                    EditLeaseTokenHash = table.Column<string>(type: SqlType("nchar(64)"), fixedLength: true, maxLength: 64, nullable: true),
                    EditLeaseHolder = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: true),
                    EditLeaseOperationKey = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: true),
                    EditLeaseExpiresAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Triage", x => x.Id);
                    table.CheckConstraint("CK_Triage_Version", "[Version] >= 0");
                    table.ForeignKey(
                        name: "FK_Triage_Cases_LinkedCaseId",
                        column: x => x.LinkedCaseId,
                        principalTable: "Cases",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Triage_IntakeReceipts_OriginReceiptId",
                        column: x => x.OriginReceiptId,
                        principalTable: "IntakeReceipts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "SentEmailEvidence",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    TriageId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    MessageIdentity = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    Subject = table.Column<string>(type: SqlType("nvarchar(500)"), maxLength: 500, nullable: false),
                    RecipientsJson = table.Column<string>(type: "TEXT", nullable: false),
                    MimeSha256 = table.Column<string>(type: SqlType("nchar(64)"), fixedLength: true, maxLength: 64, nullable: false),
                    SentAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false),
                    ChaseDueAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false),
                    Actor = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    OperationKey = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    RequestHash = table.Column<string>(type: SqlType("nchar(64)"), fixedLength: true, maxLength: 64, nullable: false),
                    Version = table.Column<long>(type: SqlType("bigint"), nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SentEmailEvidence", x => x.Id);
                    table.CheckConstraint("CK_SentEmailEvidence_Version", "[Version] >= 0");
                    table.ForeignKey(
                        name: "FK_SentEmailEvidence_Triage_TriageId",
                        column: x => x.TriageId,
                        principalTable: "Triage",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "TriageFindings",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    TriageId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    Roadworthiness = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: true),
                    Assessment = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: true),
                    SupersedesFindingId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: true),
                    Actor = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    OperationKey = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    Reason = table.Column<string>(type: SqlType("nvarchar(500)"), maxLength: 500, nullable: false),
                    RecordedAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TriageFindings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TriageFindings_TriageFindings_SupersedesFindingId",
                        column: x => x.SupersedesFindingId,
                        principalTable: "TriageFindings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_TriageFindings_Triage_TriageId",
                        column: x => x.TriageId,
                        principalTable: "Triage",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "TriageHistory",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    TriageId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    EventType = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    Actor = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    Reason = table.Column<string>(type: SqlType("nvarchar(500)"), maxLength: 500, nullable: false),
                    OperationKey = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    RequestHash = table.Column<string>(type: SqlType("nchar(64)"), fixedLength: true, maxLength: 64, nullable: false),
                    OccurredAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false),
                    BeforeVersion = table.Column<long>(type: SqlType("bigint"), nullable: false),
                    AfterVersion = table.Column<long>(type: SqlType("bigint"), nullable: false),
                    AfterState = table.Column<string>(type: SqlType("nvarchar(40)"), maxLength: 40, nullable: false),
                    AfterAssigneeId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: true),
                    AfterLinkedCaseId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TriageHistory", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TriageHistory_Triage_TriageId",
                        column: x => x.TriageId,
                        principalTable: "Triage",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "EmailResponseEvidence",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    SentEvidenceId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    MessageIdentity = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    MimeSha256 = table.Column<string>(type: SqlType("nchar(64)"), fixedLength: true, maxLength: 64, nullable: false),
                    ReceivedAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false),
                    Actor = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    OperationKey = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    RequestHash = table.Column<string>(type: SqlType("nchar(64)"), fixedLength: true, maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EmailResponseEvidence", x => x.Id);
                    table.ForeignKey(
                        name: "FK_EmailResponseEvidence_SentEmailEvidence_SentEvidenceId",
                        column: x => x.SentEvidenceId,
                        principalTable: "SentEmailEvidence",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "TriageResponseEvidenceLinks",
                columns: table => new
                {
                    TriageId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    SentEvidenceId = table.Column<Guid>(type: SqlType("uniqueidentifier"), nullable: false),
                    Actor = table.Column<string>(type: SqlType("nvarchar(200)"), maxLength: 200, nullable: false),
                    OperationKey = table.Column<string>(type: SqlType("nvarchar(100)"), maxLength: 100, nullable: false),
                    Reason = table.Column<string>(type: SqlType("nvarchar(500)"), maxLength: 500, nullable: false),
                    LinkedAtUtc = table.Column<DateTimeOffset>(type: SqlType("datetimeoffset"), nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TriageResponseEvidenceLinks", x => new { x.TriageId, x.SentEvidenceId });
                    table.ForeignKey(
                        name: "FK_TriageResponseEvidenceLinks_SentEmailEvidence_SentEvidenceId",
                        column: x => x.SentEvidenceId,
                        principalTable: "SentEmailEvidence",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_TriageResponseEvidenceLinks_Triage_TriageId",
                        column: x => x.TriageId,
                        principalTable: "Triage",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ActionHistory_AggregateType_AggregateId_OccurredAtUtc",
                table: "ActionHistory",
                columns: new[] { "AggregateType", "AggregateId", "OccurredAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_ActionHistory_AggregateType_CorrelationId",
                table: "ActionHistory",
                columns: new[] { "AggregateType", "CorrelationId" });

            migrationBuilder.CreateIndex(
                name: "IX_ActionHistory_OccurredAtUtc",
                table: "ActionHistory",
                column: "OccurredAtUtc");

            migrationBuilder.CreateIndex(
                name: "IX_EmailResponseEvidence_MessageIdentity",
                table: "EmailResponseEvidence",
                column: "MessageIdentity",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_EmailResponseEvidence_OperationKey",
                table: "EmailResponseEvidence",
                column: "OperationKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_EmailResponseEvidence_SentEvidenceId",
                table: "EmailResponseEvidence",
                column: "SentEvidenceId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_SecurityEvents_OccurredAtUtc",
                table: "SecurityEvents",
                column: "OccurredAtUtc");

            migrationBuilder.CreateIndex(
                name: "IX_SecurityEvents_SubjectId_OccurredAtUtc",
                table: "SecurityEvents",
                columns: new[] { "SubjectId", "OccurredAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_SentEmailEvidence_ChaseDueAtUtc_TriageId",
                table: "SentEmailEvidence",
                columns: new[] { "ChaseDueAtUtc", "TriageId" });

            migrationBuilder.CreateIndex(
                name: "IX_SentEmailEvidence_MessageIdentity",
                table: "SentEmailEvidence",
                column: "MessageIdentity",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_SentEmailEvidence_OperationKey",
                table: "SentEmailEvidence",
                column: "OperationKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_SentEmailEvidence_TriageId",
                table: "SentEmailEvidence",
                column: "TriageId");

            migrationBuilder.CreateIndex(
                name: "IX_Triage_CreationOperationKey",
                table: "Triage",
                column: "CreationOperationKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Triage_LinkedCaseId",
                table: "Triage",
                column: "LinkedCaseId");

            migrationBuilder.CreateIndex(
                name: "IX_Triage_OriginReceiptId",
                table: "Triage",
                column: "OriginReceiptId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Triage_SourceChannel_ExternalReceiptToken",
                table: "Triage",
                columns: new[] { "SourceChannel", "ExternalReceiptToken" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Triage_State_CreatedAtUtc",
                table: "Triage",
                columns: new[] { "State", "CreatedAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_TriageFindings_OperationKey",
                table: "TriageFindings",
                column: "OperationKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_TriageFindings_SupersedesFindingId",
                table: "TriageFindings",
                column: "SupersedesFindingId",
                unique: true,
                filter: "[SupersedesFindingId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_TriageFindings_TriageId_RecordedAtUtc",
                table: "TriageFindings",
                columns: new[] { "TriageId", "RecordedAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_TriageHistory_OperationKey",
                table: "TriageHistory",
                column: "OperationKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_TriageHistory_TriageId_OccurredAtUtc",
                table: "TriageHistory",
                columns: new[] { "TriageId", "OccurredAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_TriageResponseEvidenceLinks_OperationKey",
                table: "TriageResponseEvidenceLinks",
                column: "OperationKey",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_TriageResponseEvidenceLinks_SentEvidenceId",
                table: "TriageResponseEvidenceLinks",
                column: "SentEvidenceId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TriageResponseEvidenceLinks");

            migrationBuilder.DropTable(
                name: "EmailResponseEvidence");

            migrationBuilder.DropTable(
                name: "TriageHistory");

            migrationBuilder.DropTable(
                name: "TriageFindings");

            migrationBuilder.DropTable(
                name: "SentEmailEvidence");

            migrationBuilder.DropTable(
                name: "Triage");

            migrationBuilder.DropTable(
                name: "SecurityEvents");

            migrationBuilder.DropTable(
                name: "ActionHistory");
        }
    }
}
