param location string
@description('Region of the Web App Service plan and Web App. Defaults to the platform region; ADR-0049 allows the Web plan alone to sit in another UK region when the subscription holds no App Service quota in the platform region.')
param webLocation string = location
param tags object
param sqlAdministratorObjectId string
param sqlAdministratorLogin string
param alertEmailAddress string
@allowed([
  'disabled'
  'approved'
])
param webActivation string
param workerActivation string
param graphChangeNotificationClientStateSecretUri string
param boxConfigJsonSecretUri string
param boxClientSecretSecretUri string
@description('Versioned Key Vault secret URI containing the fine-grained GitHub token that raises problem reports as issues (ADR-0055).')
param gitHubProblemReportTokenSecretUri string
@description('The owner/name repository that receives problem reports as issues.')
param gitHubProblemReportRepository string
param boxHoldingFolderId string
param automationMcpClientSecretUri string
param automationMcpSigningCertificateSecretUris string
param automationMcpEncryptionCertificateSecretUris string
var automationMcpSigningCertificateEnvironment = [for (uri, index) in split(automationMcpSigningCertificateSecretUris, ','): {
  name: 'AutomationMcp__SigningCertificateSecretUris__${index}'
  value: trim(uri)
}]
var automationMcpEncryptionCertificateEnvironment = [for (uri, index) in split(automationMcpEncryptionCertificateSecretUris, ','): {
  name: 'AutomationMcp__EncryptionCertificateSecretUris__${index}'
  value: trim(uri)
}]
param automationMcpRedirectUris string
param dvlaApiKeySecretUri string
param dvsaClientIdSecretUri string
param dvsaClientSecretSecretUri string
param dvsaApiKeySecretUri string
param dvsaTokenUri string
param dvsaScope string
// EXT-04. EVA serves test and live from one host, so the environment is
// decided entirely by which credential pair these two URIs resolve to.
param evaClientIdSecretUri string
param evaClientSecretSecretUri string
param evaBaseUri string
param evaRequestFrom string
param evaInspectionType string
param evaInstructionEmail string
// CASE-047 B04. The Glass's adapter is Web-only and built from these at
// startup; the callback origin is derived below from the Web ingress itself.
param glassMarketValueAssessorBaseUri string
param glassEstimatorBaseUri string
param glassRepairProfileId string

var suffix =take(uniqueString(subscription().subscriptionId, resourceGroup().id, 'prod'), 10)
var prefix = 'pegasus-prod'
var telemetryDailyCapGb = json('0.5')
var transportStorageName = 'pegtrans${suffix}'
var custodyStorageName = 'pegcustody${suffix}'
var keyVaultName = 'pegasusprodkv${take(suffix, 8)}'
var documentIntelligenceName = '${prefix}-ocr-${suffix}'
var webActivationApproved = webActivation == 'approved'
// ADR-0049: the Web App keeps the classic default hostname because
// autoGeneratedDomainNameLabelScope is left unset, so the public origin is
// known before the site exists and the Worker can address the mail webhook
// whether or not Web activation is approved in the same provision.
var webHostName = '${prefix}-web-${suffix}.azurewebsites.net'
var webPublicOrigin = 'https://${webHostName}/'
var workerActivationApproved = workerActivation == 'approved-live-worker'
var blobDataOwnerRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b7e6dc6d-f1e8-4753-8033-0f276bb0955b')
var blobDataContributorRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
var queueDataContributorRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '974c5e8b-45b9-4653-ba55-5f855dd0fb88')
var queueDataMessageSenderRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'c6a89b2d-59bc-44d0-9896-0f6e12d7b80a')
var tableDataContributorRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '0a9a7e1f-b9d0-4cc4-a60d-0319b160aaa3')
var monitoringMetricsPublisherRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '3913510d-42f4-4e42-8a64-420c390055eb')
var cognitiveServicesUserRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'a97b65f3-24c7-4388-baec-2e87135dc908')
var webSqlConnectionString = 'Server=tcp:${sqlServer.properties.fullyQualifiedDomainName},1433;Database=${sqlDatabase.name};Authentication=Active Directory Managed Identity;User Id=${webIdentity.properties.clientId};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
var workerSqlConnectionString = 'Server=tcp:${sqlServer.properties.fullyQualifiedDomainName},1433;Database=${sqlDatabase.name};Authentication=Active Directory Managed Identity;User Id=${workerIdentity.properties.clientId};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: '${prefix}-logs-${suffix}'
  location: location
  tags: tags
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 31
    workspaceCapping: { dailyQuotaGb: telemetryDailyCapGb }
  }
}

resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: '${prefix}-appi-${suffix}'
  location: location
  kind: 'web'
  tags: tags
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
    DisableLocalAuth: true
  }
}

// MAIL-020: one number governs the component and workspace daily caps.
resource applicationInsightsDailyCap 'Microsoft.Insights/components/pricingPlans@2017-10-01' = {
  parent: applicationInsights
  name: 'current'
  properties: {
    planType: 'Basic'
    cap: telemetryDailyCapGb
    warningThreshold: 90
    stopSendNotificationWhenHitCap: false
  }
}

resource actionGroup 'Microsoft.Insights/actionGroups@2023-01-01' = {
  name: '${prefix}-operations'
  location: 'global'
  tags: tags
  properties: {
    groupShortName: 'PegProd'
    enabled: true
    emailReceivers: [
      {
        name: 'Pegasus production operator'
        emailAddress: alertEmailAddress
        useCommonAlertSchema: true
      }
    ]
  }
}

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  tags: tags
  properties: {
    tenantId: tenant().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enablePurgeProtection: true
    publicNetworkAccess: 'Enabled'
  }
}

resource transportStorage 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: transportStorageName
  location: location
  tags: union(tags, { purpose: 'transport-deployment' })
  sku: { name: 'Standard_LRS' }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    defaultToOAuthAuthentication: true
    minimumTlsVersion: 'TLS1_2'
    publicNetworkAccess: 'Enabled'
    supportsHttpsTrafficOnly: true
  }
}

resource transportBlobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: transportStorage
  name: 'default'
  properties: { deleteRetentionPolicy: { enabled: true, days: 7 } }
}

resource packageContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: transportBlobService
  name: 'app-package'
  properties: { publicAccess: 'None' }
}

resource transportQueueService 'Microsoft.Storage/storageAccounts/queueServices@2023-05-01' = {
  parent: transportStorage
  name: 'default'
}

resource intakeQueue 'Microsoft.Storage/storageAccounts/queueServices/queues@2023-05-01' = {
  parent: transportQueueService
  name: 'intake-work'
}

resource intakePoisonQueue 'Microsoft.Storage/storageAccounts/queueServices/queues@2023-05-01' = {
  parent: transportQueueService
  name: 'intake-work-poison'
}

resource custodyStorage 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: custodyStorageName
  location: location
  tags: union(tags, { purpose: 'custody-protection' })
  sku: { name: 'Standard_LRS' }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    defaultToOAuthAuthentication: true
    minimumTlsVersion: 'TLS1_2'
    publicNetworkAccess: 'Enabled'
    supportsHttpsTrafficOnly: true
  }
}

resource custodyBlobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: custodyStorage
  name: 'default'
  properties: { deleteRetentionPolicy: { enabled: true, days: 7 } }
}

resource transientIntakeContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: custodyBlobService
  name: 'transient-intake'
  properties: { publicAccess: 'None' }
}

resource authenticationRingContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: custodyBlobService
  name: 'authentication-ring'
  properties: { publicAccess: 'None' }
}

resource boxLinkContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: custodyBlobService
  name: 'box-links'
  properties: { publicAccess: 'None' }
}

resource sqlServer 'Microsoft.Sql/servers@2023-08-01-preview' = {
  name: '${prefix}-sql-${suffix}'
  location: location
  tags: tags
  properties: {
    administrators: {
      administratorType: 'ActiveDirectory'
      azureADOnlyAuthentication: true
      login: sqlAdministratorLogin
      principalType: 'User'
      sid: sqlAdministratorObjectId
      tenantId: tenant().tenantId
    }
    minimalTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
    restrictOutboundNetworkAccess: 'Disabled'
  }
}

resource sqlDatabase 'Microsoft.Sql/servers/databases@2023-08-01-preview' = {
  parent: sqlServer
  name: 'pegasus'
  location: location
  tags: tags
  sku: { name: 'S0', tier: 'Standard', capacity: 10 }
  properties: { maxSizeBytes: 268435456000, zoneRedundant: false }
}

resource sqlAzureServicesFirewall 'Microsoft.Sql/servers/firewallRules@2023-08-01-preview' = {
  parent: sqlServer
  name: 'AllowAzureServices'
  properties: { startIpAddress: '0.0.0.0', endIpAddress: '0.0.0.0' }
}

resource webIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: '${prefix}-web-id-${suffix}'
  location: location
  tags: tags
}

resource workerIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: '${prefix}-worker-id-${suffix}'
  location: location
  tags: tags
}

// ADR-0040: Worker posts retained bytes; no account-side storage identity or keys.
resource documentIntelligence 'Microsoft.CognitiveServices/accounts@2026-05-01' = {
  name: documentIntelligenceName
  location: location
  tags: tags
  kind: 'FormRecognizer'
  sku: { name: 'S0', tier: 'Standard' }
  properties: {
    customSubDomainName: documentIntelligenceName
    disableLocalAuth: true
    publicNetworkAccess: 'Enabled'
  }
}

resource workerDocumentIntelligenceUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(documentIntelligence.id, workerIdentity.id, cognitiveServicesUserRole)
  scope: documentIntelligence
  properties: {
    roleDefinitionId: cognitiveServicesUserRole
    principalId: workerIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource webTelemetryPublisher 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(applicationInsights.id, webIdentity.id, monitoringMetricsPublisherRole)
  scope: applicationInsights
  properties: {
    roleDefinitionId: monitoringMetricsPublisherRole
    principalId: webIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource workerTelemetryPublisher 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(applicationInsights.id, workerIdentity.id, monitoringMetricsPublisherRole)
  scope: applicationInsights
  properties: {
    roleDefinitionId: monitoringMetricsPublisherRole
    principalId: workerIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource workerTransportBlobOwner 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(transportStorage.id, workerIdentity.id, blobDataOwnerRole)
  scope: transportStorage
  properties: { roleDefinitionId: blobDataOwnerRole, principalId: workerIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource workerTransportTableContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(transportStorage.id, workerIdentity.id, tableDataContributorRole)
  scope: transportStorage
  properties: { roleDefinitionId: tableDataContributorRole, principalId: workerIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource workerTransportQueueContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(transportStorage.id, workerIdentity.id, queueDataContributorRole)
  scope: transportStorage
  properties: { roleDefinitionId: queueDataContributorRole, principalId: workerIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource webIntakeQueueSender 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(intakeQueue.id, webIdentity.id, queueDataMessageSenderRole)
  scope: intakeQueue
  properties: { roleDefinitionId: queueDataMessageSenderRole, principalId: webIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource workerTransientCustodyOwner 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(transientIntakeContainer.id, workerIdentity.id, blobDataOwnerRole)
  scope: transientIntakeContainer
  properties: { roleDefinitionId: blobDataOwnerRole, principalId: workerIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource workerBoxLinkContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(boxLinkContainer.id, workerIdentity.id, blobDataContributorRole)
  scope: boxLinkContainer
  properties: { roleDefinitionId: blobDataContributorRole, principalId: workerIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource webTransientCustodyOwner 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(transientIntakeContainer.id, webIdentity.id, blobDataOwnerRole)
  scope: transientIntakeContainer
  properties: { roleDefinitionId: blobDataOwnerRole, principalId: webIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource webAuthenticationRingContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(authenticationRingContainer.id, webIdentity.id, blobDataContributorRole)
  scope: authenticationRingContainer
  properties: { roleDefinitionId: blobDataContributorRole, principalId: webIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

resource webBoxLinkContributor 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(boxLinkContainer.id, webIdentity.id, blobDataContributorRole)
  scope: boxLinkContainer
  properties: { roleDefinitionId: blobDataContributorRole, principalId: webIdentity.properties.principalId, principalType: 'ServicePrincipal' }
}

// ADR-0049: Web runs on a Linux App Service plan as a code-deployed Web App.
// The plan is fixed compute; it can be resized within the Basic tier without a
// redeployment. Nothing here depends on a container image or registry.
resource webPlan 'Microsoft.Web/serverfarms@2024-04-01' = {
  name: '${prefix}-web-plan-${suffix}'
  location: webLocation
  kind: 'linux'
  tags: tags
  sku: { name: 'B1', tier: 'Basic', capacity: 1 }
  properties: { reserved: true }
}

resource webApp 'Microsoft.Web/sites@2024-04-01' = if (webActivationApproved) {
  name: '${prefix}-web-${suffix}'
  location: webLocation
  kind: 'app,linux'
  tags: union(tags, { 'azd-service-name': 'web' })
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${webIdentity.id}': {} } }
  properties: {
    serverFarmId: webPlan.id
    httpsOnly: true
    clientAffinityEnabled: false
    publicNetworkAccess: 'Enabled'
    // Web composes Box-backed case custody and managed document content, so it
    // needs the same Box credentials the Worker uses. App Service resolves the
    // @Microsoft.KeyVault references through the web identity, which needs Key
    // Vault Secrets User on the vault holding the referenced secrets.
    keyVaultReferenceIdentity: webIdentity.id
    siteConfig: {
      linuxFxVersion: 'DOTNETCORE|10.0'
      alwaysOn: true
      http20Enabled: true
      ftpsState: 'Disabled'
      minTlsVersion: '1.2'
      use32BitWorkerProcess: false
      webSocketsEnabled: false
      // The readiness probe the Container App used; the platform recycles an
      // instance that fails it. Liveness has no separate probe on App Service.
      healthCheckPath: '/health/ready'
      appSettings: concat([
        { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: applicationInsights.properties.ConnectionString }
        { name: 'APPLICATIONINSIGHTS_AUTHENTICATION_STRING', value: 'Authorization=AAD;ClientId=${webIdentity.properties.clientId}' }
        { name: 'APPLICATIONINSIGHTS_ENABLEADAPTIVESAMPLING', value: 'true' }
        { name: 'ASPNETCORE_ENVIRONMENT', value: 'Production' }
        // The built-in .NET image starts the app with PORT=8080; Kestrel binds
        // the same port so the platform and the app agree without a container.
        { name: 'ASPNETCORE_HTTP_PORTS', value: '8080' }
        { name: 'WEBSITES_PORT', value: '8080' }
        // ADR-0049: the release artifact is web.zip, mounted read-only by the
        // platform; nothing is built on the host.
        { name: 'WEBSITE_RUN_FROM_PACKAGE', value: '1' }
        { name: 'SCM_DO_BUILD_DURING_DEPLOYMENT', value: 'false' }
        { name: 'Runtime__Profile', value: 'Production' }
        { name: 'ConnectionStrings__Pegasus', value: webSqlConnectionString }
        { name: 'KEY_VAULT_URI', value: keyVault.properties.vaultUri }
        { name: 'TransportStorage__AccountName', value: transportStorage.name }
        { name: 'CustodyStorage__AccountName', value: custodyStorage.name }
        { name: 'CustodyStorage__ServiceUri', value: custodyStorage.properties.primaryEndpoints.blob }
        { name: 'IntakeQueue__ServiceUri', value: transportStorage.properties.primaryEndpoints.queue }
        { name: 'AZURE_CLIENT_ID', value: webIdentity.properties.clientId }
        { name: 'AzureIdentity__WebClientId', value: webIdentity.properties.clientId }
        // Mailbox administration's "add an address" resolve port alone (MAIL-002):
        // Mailbox identities and folders come only from approved mailbox leases
        // here — only the base URI, matching the Worker's Graph__BaseUri exactly.
        { name: 'Graph__BaseUri', value: 'https://graph.microsoft.com/v1.0/' }
        { name: 'Graph__TenantId', value: tenant().tenantId }
        { name: 'Graph__ChangeNotificationClientState', value: '@Microsoft.KeyVault(SecretUri=${graphChangeNotificationClientStateSecretUri})' }
        { name: 'Box__BaseUri', value: 'https://api.box.com/2.0/' }
        { name: 'Box__UploadUri', value: 'https://upload.box.com/api/2.0/' }
        { name: 'Box__RootFolderId', value: '405543781910' }
        { name: 'Box__HoldingFolderId', value: boxHoldingFolderId }
        { name: 'Box__ConfigJson', value: '@Microsoft.KeyVault(SecretUri=${boxConfigJsonSecretUri})' }
        { name: 'Box__ClientSecret', value: '@Microsoft.KeyVault(SecretUri=${boxClientSecretSecretUri})' }
        { name: 'GitHub__ProblemReports__Token', value: '@Microsoft.KeyVault(SecretUri=${gitHubProblemReportTokenSecretUri})' }
        { name: 'GitHub__ProblemReports__Repository', value: gitHubProblemReportRepository }
        { name: 'GitHub__ProblemReports__Labels', value: 'problem-report' }
        { name: 'Features__AutomationMcp', value: 'true' }
        { name: 'Features__ProviderApi', value: 'true' }
        { name: 'AutomationMcp__ClientId', value: 'pegasus-automation' }
        { name: 'AutomationMcp__KeyVaultUri', value: keyVault.properties.vaultUri }
        { name: 'AutomationMcp__ClientSecret', value: '@Microsoft.KeyVault(SecretUri=${automationMcpClientSecretUri})' }
        { name: 'Eva__ClientId', value: '@Microsoft.KeyVault(SecretUri=${evaClientIdSecretUri})' }
        { name: 'Eva__ClientSecret', value: '@Microsoft.KeyVault(SecretUri=${evaClientSecretSecretUri})' }
        { name: 'Eva__BaseUri', value: evaBaseUri }
        { name: 'Eva__RequestFrom', value: evaRequestFrom }
        { name: 'Eva__InspectionType', value: evaInspectionType }
        { name: 'Eva__InstructionEmail', value: evaInstructionEmail }
        { name: 'AutomationMcp__PublicOrigin', value: webPublicOrigin }
        { name: 'AutomationMcp__RedirectUris', value: automationMcpRedirectUris }
        // CASE-047 B04 Glass's Repair Estimate. Program.cs lists these four
        // among the Production required keys, so a Web deployment without
        // them stops at startup naming the key. The callback origin is the
        // Web App itself, exactly as AutomationMcp__PublicOrigin above.
        { name: 'Glass__MarketValueAssessorBaseUri', value: glassMarketValueAssessorBaseUri }
        { name: 'Glass__EstimatorBaseUri', value: glassEstimatorBaseUri }
        { name: 'Glass__CallbackBaseUri', value: webPublicOrigin }
        { name: 'Glass__RepairProfileId', value: glassRepairProfileId }
      ], automationMcpSigningCertificateEnvironment, automationMcpEncryptionCertificateEnvironment)
    }
  }
  dependsOn: [webTelemetryPublisher, webIntakeQueueSender]
}

// Kudu and FTP basic publishing credentials stay off; az webapp deploy uses the
// caller's Entra token.
resource webAppScmBasicAuth 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-04-01' = if (webActivationApproved) {
  parent: webApp
  name: 'scm'
  properties: { allow: false }
}

resource webAppFtpBasicAuth 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-04-01' = if (webActivationApproved) {
  parent: webApp
  name: 'ftp'
  properties: { allow: false }
}

resource webAppDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = if (webActivationApproved) {
  name: '${prefix}-web-diagnostics'
  scope: webApp
  properties: {
    workspaceId: logAnalytics.id
    logs: [
      { category: 'AppServiceHTTPLogs', enabled: true }
      { category: 'AppServiceConsoleLogs', enabled: true }
      { category: 'AppServiceAppLogs', enabled: true }
      { category: 'AppServicePlatformLogs', enabled: true }
    ]
  }
}

resource functionPlan 'Microsoft.Web/serverfarms@2024-04-01' = {
  name: '${prefix}-worker-plan-${suffix}'
  location: location
  kind: 'functionapp'
  tags: tags
  sku: { name: 'FC1', tier: 'FlexConsumption' }
  properties: { reserved: true }
}

resource workerApp 'Microsoft.Web/sites@2024-04-01' = {
  name: '${prefix}-worker-${suffix}'
  location: location
  kind: 'functionapp,linux'
  tags: union(tags, { 'azd-service-name': 'worker' })
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${workerIdentity.id}': {} } }
  properties: {
    serverFarmId: functionPlan.id
    httpsOnly: true
    publicNetworkAccess: 'Enabled'
    keyVaultReferenceIdentity: workerIdentity.id
    functionAppConfig: {
      deployment: {
        storage: {
          type: 'blobContainer'
          value: '${transportStorage.properties.primaryEndpoints.blob}${packageContainer.name}'
          authentication: { type: 'UserAssignedIdentity', userAssignedIdentityResourceId: workerIdentity.id }
        }
      }
      runtime: { name: 'dotnet-isolated', version: '10.0' }
      scaleAndConcurrency: {
        maximumInstanceCount: 20
        instanceMemoryMB: 2048
        alwaysReady: [
          {
            name: 'function:UnifiedWorkFunction'
            instanceCount: 1
          }
        ]
      }
    }
    siteConfig: {
      ftpsState: 'Disabled'
      minTlsVersion: '1.2'
      appSettings: [
        { name: 'Runtime__Profile', value: 'Production' }
        { name: 'AzureWebJobsStorage__accountName', value: transportStorage.name }
        { name: 'AzureWebJobsStorage__credential', value: 'managedidentity' }
        { name: 'AzureWebJobsStorage__clientId', value: workerIdentity.properties.clientId }
        { name: 'AzureIdentity__WorkerClientId', value: workerIdentity.properties.clientId }
        { name: 'DocumentIntelligence__Endpoint', value: documentIntelligence.properties.endpoint }
        { name: 'IntakeStorage__ServiceUri', value: custodyStorage.properties.primaryEndpoints.blob }
        { name: 'IntakeQueue__ServiceUri', value: transportStorage.properties.primaryEndpoints.queue }
        // Recovery only: every committing caller attempts exact-ID publication.
        { name: 'PendingWorkRecoverySchedule', value: '0 * * * * *' }
        { name: 'AutomaticEvaReviewSubmissionSchedule', value: '0 * * * * *' }
        { name: 'IntakeStagedArtifactReconciliationSchedule', value: '*/10 * * * * *' }
        { name: 'ApprovedInboxPollSchedule', value: '0 */5 * * * *' }
        { name: 'SentEvidencePollSchedule', value: '15 * * * * *' }
        { name: 'DueWorkSweepSchedule', value: '0 */5 * * * *' }
        { name: 'AzureWebJobs.PendingWorkRecoveryFunction.Disabled', value: workerActivationApproved ? 'false' : 'true' }
        { name: 'AzureWebJobs.UnifiedWorkFunction.Disabled', value: workerActivationApproved ? 'false' : 'true' }
        { name: 'AzureWebJobs.UnifiedWorkPoisonFunction.Disabled', value: workerActivationApproved ? 'false' : 'true' }
        { name: 'AzureWebJobs.StagedArtifactReconciliationFunction.Disabled', value: workerActivationApproved ? 'false' : 'true' }
        { name: 'AzureWebJobs.InboxRecoveryFunction.Disabled', value: workerActivationApproved ? 'false' : 'true' }
        { name: 'AzureWebJobs.SentEvidencePollFunction.Disabled', value: workerActivationApproved ? 'false' : 'true' }
        { name: 'AzureWebJobs.DueWorkSweepFunction.Disabled', value: workerActivationApproved ? 'false' : 'true' }
        { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: applicationInsights.properties.ConnectionString }
        { name: 'APPLICATIONINSIGHTS_AUTHENTICATION_STRING', value: 'Authorization=AAD;ClientId=${workerIdentity.properties.clientId}' }
        { name: 'APPLICATIONINSIGHTS_ENABLEADAPTIVESAMPLING', value: 'true' }
        { name: 'ConnectionStrings__Pegasus', value: workerSqlConnectionString }
        { name: 'KEY_VAULT_URI', value: keyVault.properties.vaultUri }
        { name: 'TransportStorage__AccountName', value: transportStorage.name }
        { name: 'CustodyStorage__AccountName', value: custodyStorage.name }
        { name: 'Graph__BaseUri', value: 'https://graph.microsoft.com/v1.0/' }
        { name: 'Graph__TenantId', value: tenant().tenantId }
        { name: 'Graph__ChangeNotificationUrl', value: '${webPublicOrigin}hooks/microsoft-graph/mail' }
        { name: 'Graph__ChangeNotificationClientState', value: '@Microsoft.KeyVault(SecretUri=${graphChangeNotificationClientStateSecretUri})' }
        { name: 'Box__BaseUri', value: 'https://api.box.com/2.0/' }
        { name: 'Box__UploadUri', value: 'https://upload.box.com/api/2.0/' }
        { name: 'Box__RootFolderId', value: '405543781910' }
        { name: 'Box__HoldingFolderId', value: boxHoldingFolderId }
        { name: 'Box__ConfigJson', value: '@Microsoft.KeyVault(SecretUri=${boxConfigJsonSecretUri})' }
        { name: 'Box__ClientSecret', value: '@Microsoft.KeyVault(SecretUri=${boxClientSecretSecretUri})' }
        { name: 'Dvla__BaseUri', value: 'https://driver-vehicle-licensing.api.gov.uk/vehicle-enquiry/v1/' }
        { name: 'Dvla__ApiKey', value: '@Microsoft.KeyVault(SecretUri=${dvlaApiKeySecretUri})' }
        { name: 'Dvsa__BaseUri', value: 'https://history.mot.api.gov.uk/v1/trade/vehicles/registration/' }
        { name: 'Dvsa__TokenUri', value: dvsaTokenUri }
        { name: 'Dvsa__ClientId', value: '@Microsoft.KeyVault(SecretUri=${dvsaClientIdSecretUri})' }
        { name: 'Dvsa__ClientSecret', value: '@Microsoft.KeyVault(SecretUri=${dvsaClientSecretSecretUri})' }
        { name: 'Eva__ClientId', value: '@Microsoft.KeyVault(SecretUri=${evaClientIdSecretUri})' }
        { name: 'Eva__ClientSecret', value: '@Microsoft.KeyVault(SecretUri=${evaClientSecretSecretUri})' }
        { name: 'Eva__BaseUri', value: evaBaseUri }
        { name: 'Eva__RequestFrom', value: evaRequestFrom }
        { name: 'Eva__InspectionType', value: evaInspectionType }
        { name: 'Eva__InstructionEmail', value: evaInstructionEmail }
        { name: 'Dvsa__ApiKey', value: '@Microsoft.KeyVault(SecretUri=${dvsaApiKeySecretUri})' }
        { name: 'Dvsa__Scope', value: dvsaScope }
      ]
    }
  }
  dependsOn: [
    workerTransportBlobOwner
    workerTransportQueueContributor
    workerTransportTableContributor
    workerTelemetryPublisher
    workerDocumentIntelligenceUser
  ]
}

resource webHttp5xxAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = if (webActivationApproved) {
  name: '${prefix}-web-http5xx'
  location: 'global'
  tags: tags
  properties: {
    description: 'Pegasus production Web returned more than one HTTP 5xx response in five minutes.'
    severity: 1
    enabled: true
    scopes: [webApp.id]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT5M'
    autoMitigate: true
    targetResourceType: 'Microsoft.Web/sites'
    targetResourceRegion: webLocation
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'WebHttp5xx'
          metricNamespace: 'Microsoft.Web/sites'
          metricName: 'Http5xx'
          operator: 'GreaterThan'
          timeAggregation: 'Total'
          threshold: 1
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      { actionGroupId: actionGroup.id }
    ]
  }
}

resource applicationExceptionAlert 'Microsoft.Insights/scheduledQueryRules@2023-12-01' = {
  name: '${prefix}-application-exceptions'
  location: location
  tags: tags
  properties: {
    displayName: 'Pegasus production application exceptions'
    description: 'One or more correlated Web or Worker exceptions were recorded.'
    severity: 2
    enabled: true
    evaluationFrequency: 'PT5M'
    scopes: [logAnalytics.id]
    targetResourceTypes: ['Microsoft.OperationalInsights/workspaces']
    windowSize: 'PT15M'
    criteria: {
      allOf: [
        {
          query: '''
            let CorrelatedExceptions = AppExceptions
              | where TimeGenerated > ago(15m)
              | extend ExceptionSignature = strcat(
                  coalesce(ExceptionType, 'UnknownException'),
                  '|',
                  substring(replace_regex(coalesce(OuterMessage, InnermostMessage, Message, ''), @'[0-9a-fA-F]{8}-[0-9a-fA-F-]{27,}', '<id>'), 0, 512)),
                  CorrelationId = tostring(OperationId)
              | where isnotempty(CorrelationId)
              | summarize LastSeen=max(TimeGenerated), ExceptionRows=count(), AppRole=take_any(AppRoleName)
                  by ExceptionSignature, CorrelationId;
            let FailedRecentOperations = AppRequests
              | where TimeGenerated > ago(5m) and Success == false
              | where isnotempty(OperationId)
              | summarize by CorrelationId=tostring(OperationId);
            let FailedRecent = CorrelatedExceptions
              | where LastSeen > ago(5m)
              | join kind=inner FailedRecentOperations on CorrelationId
              | project ExceptionSignature, AppRole, LastSeen, Reason='failed_operation';
            let PersistentCorrelated = CorrelatedExceptions
              | summarize DistinctOperations=dcount(CorrelationId), LastSeen=max(LastSeen), AppRole=take_any(AppRole)
                  by ExceptionSignature
              | where DistinctOperations >= 3
              | project ExceptionSignature, AppRole, LastSeen, Reason='repeated_operations';
            let PersistentUncorrelated = AppExceptions
              | where TimeGenerated > ago(15m) and isempty(OperationId)
              | extend ExceptionSignature = strcat(
                  coalesce(ExceptionType, 'UnknownException'),
                  '|',
                  substring(replace_regex(coalesce(OuterMessage, InnermostMessage, Message, ''), @'[0-9a-fA-F]{8}-[0-9a-fA-F-]{27,}', '<id>'), 0, 512)),
                  MinuteBucket=bin(TimeGenerated, 1m)
              | summarize AppRole=take_any(AppRoleName), LastSeen=max(TimeGenerated)
                  by ExceptionSignature, MinuteBucket
              | summarize DistinctMinuteBuckets=count(), LastSeen=max(LastSeen), AppRole=take_any(AppRole)
                  by ExceptionSignature
              | where DistinctMinuteBuckets >= 3
              | project ExceptionSignature, AppRole, LastSeen, Reason='repeated_uncorrelated';
            union FailedRecent, PersistentCorrelated, PersistentUncorrelated
              | summarize ExceptionCount=count()
            '''
          timeAggregation: 'Total'
          metricMeasureColumn: 'ExceptionCount'
          operator: 'GreaterThan'
          threshold: 0
          failingPeriods: {
            numberOfEvaluationPeriods: 1
            minFailingPeriodsToAlert: 1
          }
        }
      ]
    }
    autoMitigate: true
    actions: {
      actionGroups: [actionGroup.id]
    }
  }
}

output webAppName string = webActivationApproved ? webApp!.name : ''
output webAppHostName string = webActivationApproved ? webApp!.properties.defaultHostName : ''
output webPlanName string = webPlan.name
output webIdentityName string = webIdentity.name
output webIdentityClientId string = webIdentity.properties.clientId
output workerAppName string = workerApp.name
output workerIdentityName string = workerIdentity.name
output workerIdentityClientId string = workerIdentity.properties.clientId
output documentIntelligenceAccountId string = documentIntelligence.id
output documentIntelligenceEndpoint string = documentIntelligence.properties.endpoint
output sqlServerFqdn string = sqlServer.properties.fullyQualifiedDomainName
output sqlDatabaseName string = sqlDatabase.name
output transportStorageAccountName string = transportStorage.name
output custodyStorageAccountName string = custodyStorage.name
output keyVaultName string = keyVault.name
output applicationInsightsName string = applicationInsights.name
output logAnalyticsWorkspaceName string = logAnalytics.name
output actionGroupName string = actionGroup.name
