-- ============================================================================
-- TKT-140 drain phase — AFTER-state verification (READ-ONLY; one window).
-- Generated by gen-after-sql.mjs over the dry-run's 118 enumerated row ids.
-- Drain window started: 2026-07-10T15:28:03Z
-- ============================================================================
\timing on
SET ROLE csadmin;

\echo '=== AFTER: inbound_email totals ==='
SELECT count(*) AS inbound_total,
       count(*) FILTER (WHERE case_id IS NULL) AS inbound_uncased
  FROM inbound_email;

\echo '=== AFTER: the 118 enumerated dry-run rows — linkage + attention state ==='
WITH enumerated(id) AS (VALUES
  ('6622679f-6956-474f-882b-17476338b1e4'::uuid),
  ('4e73fe72-e215-46ba-99d3-42aee6f03317'::uuid),
  ('973bbcf3-f606-45e8-a8da-ca202f52a65f'::uuid),
  ('7b7e24e9-be41-4fa7-870a-77968dbab1f7'::uuid),
  ('5899538d-564e-4fcf-898c-13304dc9f5de'::uuid),
  ('e85a7386-99e6-4089-a805-c17878969a0d'::uuid),
  ('db3ace97-f9a1-4a10-9c8b-763b9d8e109a'::uuid),
  ('edf92584-d5f2-48d0-bed1-95cf5002f5b8'::uuid),
  ('47266d55-4fa5-4ba3-8765-54a3b476a181'::uuid),
  ('b2333ee7-4e42-445f-8079-4ed823dcbf23'::uuid),
  ('a1f22ce3-1aee-4749-9a13-02e4060ceb78'::uuid),
  ('d71e30e7-43e8-4d62-9ece-7b4b484eedd0'::uuid),
  ('3e727ed5-9d65-46c3-a2fd-40f37c028752'::uuid),
  ('aa536fe6-81bc-43d7-a768-ccb38fc93f3f'::uuid),
  ('3bc6a550-0e10-4d05-b443-36a59f9594cc'::uuid),
  ('5ba72558-0f89-468c-8b83-6a7931416692'::uuid),
  ('0ae7e88c-a90c-4763-b2cd-4a07f1d2f7fd'::uuid),
  ('46f60420-aee5-4326-bcdb-ce80c3842ffc'::uuid),
  ('f7c79b42-78c8-4962-8afb-464779cca01e'::uuid),
  ('58ce43ca-47b8-448f-8d85-dec1b66efe90'::uuid),
  ('f516d4f9-e505-4b6d-b519-f8c1be37f5d3'::uuid),
  ('77d45fb8-23bc-40d1-9056-a7f425e1c1c5'::uuid),
  ('ccd95a95-046e-44b1-a32c-162e32d500f2'::uuid),
  ('055a5b41-358f-4ae9-b0c4-81cd9efe7892'::uuid),
  ('87ec3a51-6fa8-48b7-9bd5-ad1ab15511e0'::uuid),
  ('c0e74ce8-e950-4e99-a5c6-8101b2ad27f5'::uuid),
  ('0367d3f7-e362-4835-8115-617e68872858'::uuid),
  ('1e742ad8-936b-4413-8988-aef23fa66b2d'::uuid),
  ('0ddc8326-c9c6-4c02-9c5e-20ed789f2ccd'::uuid),
  ('e31f91cd-425e-4b1d-b7aa-8b6bf3c31dea'::uuid),
  ('5b5f4dd0-cf98-4eed-9673-22eef5aacad3'::uuid),
  ('f2c4ef55-c6f9-47a3-8642-2c45332c9127'::uuid),
  ('85ed4d4d-b41a-4810-bc24-3287d6097d56'::uuid),
  ('3bca40b3-e3aa-4dad-bae0-72fbdcd6fa6d'::uuid),
  ('2930e8b6-f8e5-46e7-b568-6e2b5db5697c'::uuid),
  ('c0952c38-a269-4f20-8a51-2dd38f50d9ac'::uuid),
  ('ce1f8f9a-194f-4f89-a763-3f0bcb59f635'::uuid),
  ('c9f82a2a-6a0d-4848-9014-5ffc42fd3ac9'::uuid),
  ('02bfb1f2-950e-492f-a5dc-7fca58dc2bf6'::uuid),
  ('a65e133e-e752-4264-af8c-204fbe49b2a7'::uuid),
  ('d22008d7-f33f-44db-9d4f-a6b295f0c391'::uuid),
  ('bf7ca211-32c4-4e13-94ce-3c1d87fadee2'::uuid),
  ('0183a12f-802b-49c8-b4be-1582e31ff630'::uuid),
  ('04c1c6c1-b62a-4740-8220-854a317106e8'::uuid),
  ('984dd3ab-23a4-406f-bf4f-af2a76a04d14'::uuid),
  ('457371c6-073c-4146-970d-5b6ea1312d46'::uuid),
  ('1090cef2-0cdb-4825-a962-f117e9425a84'::uuid),
  ('8edbf3a2-8bcd-4119-bbdd-fb3a030e63b8'::uuid),
  ('4b9b99da-dfa3-4661-b1e3-5d8c3d688446'::uuid),
  ('43521747-c7df-45f2-9fc7-daaac49b350e'::uuid),
  ('97bcf4a6-d889-49f9-a697-5e6e5465462f'::uuid),
  ('55d89fc8-de05-4f9a-8ec2-82df08ba4a41'::uuid),
  ('b8a2e8e9-6ab2-4356-81f7-ecb3857b0780'::uuid),
  ('f4713001-694c-4701-9154-b81c482110f5'::uuid),
  ('974dfb68-67fc-437e-a388-0b74b2a574cb'::uuid),
  ('898225f7-3863-43be-97fa-f57401ad80c5'::uuid),
  ('d4581837-817f-4e20-ae2b-f14e695e41ad'::uuid),
  ('dd84dd7d-762a-451b-97c7-fda175462da3'::uuid),
  ('ace1bfb8-487b-4f4a-9e37-f6465fb7852e'::uuid),
  ('1ab4d16f-8dc1-4784-a311-370285c097c6'::uuid),
  ('1da5add6-07b7-48d1-a55e-2d5280fe6bd0'::uuid),
  ('ff1bf2e6-a6e8-4dc9-957e-961a3b23c7e5'::uuid),
  ('20f64209-7fd9-4942-b82e-35d5caa2cbb9'::uuid),
  ('84c72717-21b4-44d9-a7ad-a34c8048cf93'::uuid),
  ('940467dd-f024-4cc2-b1b5-364b6e5622a5'::uuid),
  ('6cbec582-204a-4f4d-9677-3106e3b23625'::uuid),
  ('5db226a7-9e8b-4f48-a04f-eed69a0cf9a9'::uuid),
  ('1c2b100c-eaec-44a8-9b0f-a08ec611f638'::uuid),
  ('637f1632-864a-447a-bd30-b1e4956acc67'::uuid),
  ('0cf6ce4b-7c69-4edd-93dd-2243d0a8c38a'::uuid),
  ('48bab1eb-dd5a-4fc6-aeee-a9409aee48b5'::uuid),
  ('bdbe2b55-3e37-449e-a48b-737d4dbccb42'::uuid),
  ('2ff5cfc5-8b00-4446-9a70-677a075d26f6'::uuid),
  ('1563861e-1349-4c58-96d1-5bce7deb7aa0'::uuid),
  ('c19d4239-8dc7-4008-a4f1-b2f540b404d6'::uuid),
  ('bcfcfbc8-eb58-4580-8cbc-b7f5c58cbcb9'::uuid),
  ('914d50ca-1bb8-4255-8d2a-9145ea2a46cd'::uuid),
  ('eb0ffc2a-f620-4ea4-acd4-9a046c5f080a'::uuid),
  ('dfd0909b-f528-4be1-a0da-a6a83907b8df'::uuid),
  ('b29417b5-7b10-4651-8cc7-2874295472f0'::uuid),
  ('6add7844-974f-456b-97af-fa67db8819f6'::uuid),
  ('9d4f0708-3ca5-45fc-a55b-d264ab9d1e45'::uuid),
  ('65e46447-0aa3-4eaa-80da-fe565f6698df'::uuid),
  ('b8e69c8f-1eae-4603-bd50-28f8622284b7'::uuid),
  ('2749abce-dff3-4be0-a4dd-8cb75a1218af'::uuid),
  ('f9a77fcc-3362-440a-9223-83a721b3c01a'::uuid),
  ('4ab9051d-8b1b-4ad4-809f-28f3b25e8cdf'::uuid),
  ('0a9a28d9-5497-4672-a5b9-90e728219ff4'::uuid),
  ('a5b08995-0e26-45f8-a9c2-d98a68ed0352'::uuid),
  ('988dd47e-2021-48bc-ba2c-bb3a5815d18e'::uuid),
  ('b4d57b5b-b254-446b-ac94-c67826f01da2'::uuid),
  ('660b5eb3-cdaf-41c3-864d-25ea7eb224b5'::uuid),
  ('3b5b1a6e-78f1-460c-b0bb-48246ebf9c77'::uuid),
  ('60343616-6edd-4ef4-a4c9-446975061399'::uuid),
  ('19c4549d-5df8-47fd-b7ba-d88778298f78'::uuid),
  ('bda17710-a257-468a-9d9a-d27d84534e69'::uuid),
  ('f3e77a3a-ae78-4d8d-8975-267617038916'::uuid),
  ('6598313d-8426-4138-99aa-57a67e66d222'::uuid),
  ('6ba5500e-1741-4199-8f7e-2b30c8d5034e'::uuid),
  ('fa11908f-a49f-4398-ac90-31a8f6297fef'::uuid),
  ('9e7bf40f-3505-43e5-ae20-60306a780221'::uuid),
  ('01dff2b5-edf1-46e2-aee6-cb100ffdcd68'::uuid),
  ('d731354e-9a4d-4c8f-804a-565f9a8c1d00'::uuid),
  ('d6116210-f0bd-4560-94de-2e831cf4421f'::uuid),
  ('1b3209e9-fcce-414f-bd37-b4ca8d375069'::uuid),
  ('5c5364a7-8d47-4715-b2ba-e4297c7c56a8'::uuid),
  ('f8924497-e68b-4af1-9c08-d209c864474d'::uuid),
  ('eb399785-8759-4a05-8e74-1bd353a6a877'::uuid),
  ('f7250355-09f4-413c-ad70-a0e38d8f9fc0'::uuid),
  ('6be87dc6-f6cc-4033-8e64-0481b993f797'::uuid),
  ('307cae55-d927-4171-960b-bed0cb7859c0'::uuid),
  ('8a121f17-c136-404f-9e43-c3f5b8ddb53a'::uuid),
  ('c4202cfe-12f5-4d9a-8073-304f72afab08'::uuid),
  ('f9c04399-6e08-45b7-805e-bdd753190f92'::uuid),
  ('a36da0bf-4b19-4ef6-a81f-19265d1b3ff6'::uuid),
  ('0e151228-0e36-4744-a299-ea543f4506e8'::uuid),
  ('83e6d271-270d-404b-8588-a20ab04f11b6'::uuid),
  ('e22e9b15-5d6b-4900-a8bc-9d92f4e5f31c'::uuid)
)
SELECT count(*)                                            AS enumerated_rows,
       count(*) FILTER (WHERE ie.case_id IS NOT NULL)      AS now_linked_to_case,
       count(*) FILTER (WHERE ie.case_id IS NULL)          AS still_uncased,
       count(*) FILTER (WHERE ie.attention_reason = 'unable_to_locate') AS stamped_unable_to_locate,
       count(*) FILTER (WHERE ie.case_id IS NULL AND ie.attention_reason IS NULL) AS uncased_unstamped
  FROM enumerated e
  JOIN inbound_email ie ON ie.id = e.id;

\echo '=== AFTER: retro-channel cases (intake_channel_kind_code=100000003) — Held invariant check ==='
SELECT count(*) AS retro_cases,
       count(*) FILTER (WHERE status_code = (SELECT code FROM choice_case_status WHERE name = 'needs_review')) AS status_needs_review,
       count(*) FILTER (WHERE on_hold IS TRUE)      AS on_hold_true,
       count(*) FILTER (WHERE case_po IS NOT NULL)  AS with_case_po,
       count(*) FILTER (WHERE created_at >= now() - interval '12 hours') AS created_last_12h
  FROM case_
 WHERE intake_channel_kind_code = 100000003;

\echo '=== AFTER: retro-channel cases created in the drain window (detail, newest 40) ==='
SELECT c.id, c.case_ref, c.vrm, cs.name AS status, c.on_hold, c.case_po, c.created_at
  FROM case_ c
  LEFT JOIN choice_case_status cs ON cs.code = c.status_code
 WHERE c.intake_channel_kind_code = 100000003
   AND c.created_at >= now() - interval '12 hours'
 ORDER BY c.created_at DESC
 LIMIT 40;

\echo '=== AFTER: retro audit action totals (compare enum-retro-audit-events.csv) ==='
SELECT ca.name AS action, count(*) AS events,
       count(*) FILTER (WHERE ae.occurred_at >= now() - interval '12 hours') AS last_12h
  FROM audit_event ae
  JOIN choice_audit_action ca ON ca.code = ae.action_code
 WHERE ca.name IN ('retro_case_created', 'retro_case_linked', 'retro_reconstruction_failed')
 GROUP BY ca.name ORDER BY ca.name;

\echo '=== AFTER: mint-guard refusals (any new since the dry-run?) ==='
SELECT ae.occurred_at, left(ae.name, 140) AS summary
  FROM audit_event ae
 WHERE ae.name LIKE 'Retro create refused%'
 ORDER BY ae.occurred_at;

RESET ROLE;
