using System.Text.RegularExpressions;
namespace Pegasus.Core.Intake;
public sealed partial class BcInstructionExtractionPolicy:IInstructionExtractionPolicy,IInstructionDocumentProfile,IInstructionFieldRoles
{
 public const string Key="bc_instruction";public const int Version=1;public const string SupportedPrincipalCode="BC";public const string DocumentProfileKeyValue="bc_instruction_document";
 static readonly InstructionFieldEngine.FieldDefinition[] D=[new("Claimant name",["Re Client"],PartyRole:"claimant"),new("Claim reference",["Contextual RTA reference"],PartyRole:"principal",ReferenceRole:"principal"),new("Vehicle registration",["Registered number"],IsValidTyped:InstructionFieldEngine.IsUkRegistration,CanonicalValue:InstructionFieldEngine.NormalizeRegistration,PartyRole:"claimant"),new("Incident date",["Accident"],IsValidTyped:v=>InstructionFieldEngine.ParseDate(v)is not null,CanonicalValue:InstructionFieldEngine.CanonicalDate,PartyRole:"claimant"),new("Instruction date",["Header date"],IsValidTyped:v=>InstructionFieldEngine.ParseDate(v)is not null,CanonicalValue:InstructionFieldEngine.CanonicalDate,PartyRole:"instruction"),new("Inspection address",["Address"],IsRequired:false,PartyRole:"inspection-location"),new("Requested inspection method",["Requested inspection method"],IsRequired:false,PartyRole:"requested-work"),new("Vehicle make",["Vehicle make"],IsRequired:false,PartyRole:"claimant"),new("Vehicle model",["Vehicle model"],IsRequired:false,PartyRole:"claimant"),new("Accident circumstances",["Accident circumstances"],IsRequired:false,PartyRole:"claimant"),new("Inspection date",["Completed inspection date"],IsRequired:false,IsValidTyped:v=>InstructionFieldEngine.ParseDate(v)is not null,CanonicalValue:InstructionFieldEngine.CanonicalDate,PartyRole:"inspection"),new("VAT status",["VAT status"],IsRequired:false,PartyRole:"claimant")];static readonly InstructionFieldEngine.LabelRegexCache C=new(D);
 public string PrincipalCode=>"BC";public string DocumentProfileKey=>DocumentProfileKeyValue;public int DocumentProfileVersion=>1;public InstructionDocumentSignature Signature=>new(InstructionDocumentSignature.InstructionRole,["Baker & Coleman","registered number","Re:","Client:"],["Connexus Vehicle Assessors","Exclusive Vehicle Assessors"]);public IReadOnlyDictionary<string,InstructionFieldRole>FieldRoles{get;}=D.ToDictionary(x=>x.Name,x=>new InstructionFieldRole(x.PartyRole,x.ReferenceRole),StringComparer.Ordinal);
 public InstructionExtractionResult Extract(IntakeSourceReadResult readResult,DateTimeOffset processedAtUtc,EstablishedPrincipalContext principalContext){if(readResult.Status!=IntakeSourceReadStatus.Readable||readResult.IsIncomplete)throw new ArgumentException("BC extraction requires complete readable content.",nameof(readResult));if(principalContext.PrincipalCode!="BC")throw new ArgumentException("The established principal is not BC.",nameof(principalContext));var(f,m,e)=InstructionFieldEngine.ExtractFields(readResult.Content.SelectMany(Fields).ToArray(),D,C,processedAtUtc);var v=f.ToDictionary(x=>x.Name,x=>x.SuggestedValue,StringComparer.Ordinal);var d=new InstructionDraft("BC",InstructionFieldEngine.TypedString(v["Claimant name"],300),InstructionFieldEngine.TypedString(v["Claim reference"],100),InstructionFieldEngine.NormalizeRegistration(v["Vehicle registration"]),InstructionFieldEngine.TypedString(v["Vehicle make"],100),InstructionFieldEngine.TypedString(v["Vehicle model"],100),null,InstructionFieldEngine.TypedString(v["Accident circumstances"],2000),InstructionFieldEngine.ParseDate(v["Incident date"]),InstructionFieldEngine.ParseDate(v["Instruction date"]),InstructionFieldEngine.TypedString(v["Inspection address"],1000),InstructionFieldEngine.ParseDate(v["Inspection date"]),null,InstructionFieldEngine.TypedString(v["VAT status"],100),null,null);return new(InstructionPolicyApplicability.Applicable,[..e,new(IntakeEvidenceSource.Sender,IntakeEvidenceStrength.Strong,IntakeEvidenceFinding.SupportsPrincipal,"established-principal",$"Principal BC was established by {principalContext.PolicyKey} v{principalContext.PolicyVersion}.")],f,d,m,Key,Version);}
 static IEnumerable<IntakeContentFragment>Fields(IntakeContentFragment f){var t=f.Text.Replace("\r\n","\n",StringComparison.Ordinal).Replace('\r','\n');var dear=Dear().Match(t);var sign=Sign().Match(t);if(!dear.Success||!sign.Success)yield break;var h=t[..dear.Index];var b=t[dear.Index..sign.Index];foreach(Match x in Ref().Matches(h))yield return L(f,"Contextual RTA reference",x.Groups["v"].Value);foreach(Match x in Date().Matches(h))yield return L(f,"Header date",x.Groups["v"].Value);foreach(Match x in Client().Matches(b))yield return L(f,"Re Client",x.Groups["v"].Value);foreach(Match x in Accident().Matches(b))yield return L(f,"Accident",x.Groups["v"].Value);foreach(Match x in Address().Matches(b))yield return L(f,"Address",x.Groups["v"].Value);foreach(Match x in Vrm().Matches(b))yield return L(f,"Registered number",x.Groups["v"].Value);if(Physical().IsMatch(b))yield return L(f,"Requested inspection method","Physical vehicle inspection");}
 static IntakeContentFragment L(IntakeContentFragment f,string l,string v)=>f with{Text=$"{l}: {v.Trim()}"};
 [GeneratedRegex(@"(?im)^\s*Dear\s+Sirs\s*$",RegexOptions.CultureInvariant,100)]private static partial Regex Dear();[GeneratedRegex(@"(?im)^\s*Baker\s*&\s*Coleman\s+Solicitors\s+Limited\s*$",RegexOptions.CultureInvariant,100)]private static partial Regex Sign();[GeneratedRegex(@"(?im)^\s*(?<v>RTA\d+\.\d+/[A-Z]+/[^\r\n]+)\s*$",RegexOptions.CultureInvariant,100)]private static partial Regex Ref();[GeneratedRegex(@"(?im)^\s*(?<v>\d{1,2}(?:st|nd|rd|th)?\s+[A-Za-z]+\s+\d{4})\s*$",RegexOptions.CultureInvariant,100)]private static partial Regex Date();[GeneratedRegex(@"(?im)^\s*Re\s*:\s*Client\s*:[ \t]*(?<v>[^\r\n]+)",RegexOptions.CultureInvariant,100)]private static partial Regex Client();[GeneratedRegex(@"(?im)^\s*Accident\s*:[ \t]*(?<v>[^\r\n]+)",RegexOptions.CultureInvariant,100)]private static partial Regex Accident();[GeneratedRegex(@"(?im)^\s*Address\s*:[ \t]*(?<v>[^\r\n]*)",RegexOptions.CultureInvariant,100)]private static partial Regex Address();[GeneratedRegex(@"(?im)registered\s+number[ \t]+(?<v>[A-Z0-9 ]+?)[ \t]*,",RegexOptions.CultureInvariant,100)]private static partial Regex Vrm();[GeneratedRegex(@"(?i)arrange\s+to\s+inspect\s+our\s+client['’]s\s+vehicle",RegexOptions.CultureInvariant,100)]private static partial Regex Physical();
}
