<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CollisionRenderer.Cli</RootNamespace>
    <AssemblyName>collisionrenderer</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CollisionRenderer.Core\CollisionRenderer.Core.csproj" />
  </ItemGroup>

</Project>
