<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CollisionDocNet.Core\CollisionDocNet.Core.csproj" />
    <ProjectReference Include="..\CollisionDocNet.Model\CollisionDocNet.Model.csproj" />
  </ItemGroup>
</Project>
