<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CollisionRenderer.Api</RootNamespace>
    <AssemblyName>CollisionRenderer.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CollisionRenderer.Core\CollisionRenderer.Core.csproj" />
  </ItemGroup>

</Project>
