using System.Text.RegularExpressions;
namespace Pegasus.Core.Intake;

#pragma warning disable CA1725

public sealed partial class AlsInstructionExtractionPolicy : IInstructionExtractionPolicy, IInstructionDocumentProfile, IInstructionFieldRoles
{
    public const string Key = "als_instruction"; public const int Version = 1; public const string SupportedPrincipalCode = "ALS"; public const string DocumentProfileKeyValue = "als_instruction_document";
    static readonly InstructionFieldEngine.FieldDefinition[] Definitions = [new("Claimant name", ["Client name"], PartyRole: "claimant"), new("Vehicle owner", ["Vehicle owner"], IsRequired: false, PartyRole: "owner"), new("Claim reference", ["Our Reference"], PartyRole: "principal", ReferenceRole: "principal"), new("Vehicle registration", ["Client registration"], IsValidTyped: InstructionFieldEngine.IsUkRegistration, CanonicalValue: InstructionFieldEngine.NormalizeRegistration, PartyRole: "claimant"), new("Vehicle make", ["Client vehicle make"], PartyRole: "claimant"), new("Vehicle model", ["Client vehicle model"], IsRequired: false, PartyRole: "claimant"), new("Incident date", ["Accident Date"], IsValidTyped: v => InstructionFieldEngine.ParseDate(v) is not null, CanonicalValue: InstructionFieldEngine.CanonicalDate, PartyRole: "claimant"), new("Instruction date", ["Header date"], IsValidTyped: v => InstructionFieldEngine.ParseDate(v) is not null, CanonicalValue: InstructionFieldEngine.CanonicalDate, PartyRole: "instruction"), new("Inspection address", ["Vehicle location"], IsRequired: false, PartyRole: "inspection-location"), new("Accident circumstances", ["Accident Circumstances"], IsRequired: false, PartyRole: "claimant"), new("VAT status", ["VAT Registered"], IsRequired: false, PartyRole: "claimant"), new("Repairer", ["Repairer"], IsRequired: false, PartyRole: "repairer"), new("Claimant address", ["Client address"], IsRequired: false, PartyRole: "claimant"), new("Vehicle class", ["Vehicle Category"], IsRequired: false, PartyRole: "vehicle-class"), new("Inspection date", ["Completed inspection date"], IsRequired: false, IsValidTyped: v => InstructionFieldEngine.ParseDate(v) is not null, CanonicalValue: InstructionFieldEngine.CanonicalDate, PartyRole: "inspection")]; static readonly InstructionFieldEngine.LabelRegexCache Cache = new(Definitions);
    public string PrincipalCode => SupportedPrincipalCode; public string DocumentProfileKey => DocumentProfileKeyValue; public int DocumentProfileVersion => 1; public InstructionDocumentSignature Signature => new(InstructionDocumentSignature.InstructionRole, ["Auto Logistic Solutions", "Vehicle Reg:", "Vehicle Model:"], ["Connexus Vehicle Assessors", "Exclusive Vehicle Assessors"]); public IReadOnlyDictionary<string, InstructionFieldRole> FieldRoles { get; } = Definitions.ToDictionary(x => x.Name, x => new InstructionFieldRole(x.PartyRole, x.ReferenceRole), StringComparer.Ordinal);
    public InstructionExtractionResult Extract(IntakeSourceReadResult r, DateTimeOffset at, EstablishedPrincipalContext p) { if (r.Status != IntakeSourceReadStatus.Readable || r.IsIncomplete) throw new ArgumentException("ALS extraction requires complete readable content.", nameof(r)); if (p.PrincipalCode != SupportedPrincipalCode) throw new ArgumentException("The established principal is not ALS.", nameof(p)); var (f, m, e) = InstructionFieldEngine.ExtractFields(r.Content.SelectMany(Fields).ToArray(), Definitions, Cache, at); var v = f.ToDictionary(x => x.Name, x => x.SuggestedValue, StringComparer.Ordinal); var d = new InstructionDraft("ALS", InstructionFieldEngine.TypedString(v["Claimant name"], 300), InstructionFieldEngine.TypedString(v["Claim reference"], 100), InstructionFieldEngine.NormalizeRegistration(v["Vehicle registration"]), InstructionFieldEngine.TypedString(v["Vehicle make"], 100), InstructionFieldEngine.TypedString(v["Vehicle model"], 100), null, InstructionFieldEngine.TypedString(v["Accident circumstances"], 2000), InstructionFieldEngine.ParseDate(v["Incident date"]), InstructionFieldEngine.ParseDate(v["Instruction date"]), InstructionFieldEngine.TypedString(v["Inspection address"], 1000), InstructionFieldEngine.ParseDate(v["Inspection date"]), null, InstructionFieldEngine.TypedString(v["VAT status"], 100), null, null); return new(InstructionPolicyApplicability.Applicable, [.. e, new(IntakeEvidenceSource.Sender, IntakeEvidenceStrength.Strong, IntakeEvidenceFinding.SupportsPrincipal, "established-principal", $"Principal ALS was established by {p.PolicyKey} v{p.PolicyVersion}.")], f, d, m, Key, Version); }
    static IEnumerable<IntakeContentFragment> Fields(IntakeContentFragment f) { var t = f.Text.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n'); var dear = Dear().Match(t); var sign = Sign().Match(t); if (!dear.Success || !sign.Success || sign.Index <= dear.Index) yield break; var h = t[..dear.Index]; var b = t[dear.Index..sign.Index]; foreach (Match x in Ref().Matches(h)) yield return L(f, "Our Reference", x.Groups["v"].Value); foreach (Match x in Date().Matches(h)) yield return L(f, "Header date", x.Groups["v"].Value); foreach (Match x in Accident().Matches(b)) yield return L(f, "Accident Date", x.Groups["v"].Value); foreach (Match x in Circ().Matches(b)) yield return L(f, "Accident Circumstances", x.Groups["v"].Value); foreach (Match x in Party().Matches(b)) { yield return L(f, "Client name", x.Groups["client"].Value); yield return L(f, "Client address", x.Groups["address"].Value); } foreach (Match x in Owner().Matches(b)) yield return L(f, "Vehicle owner", x.Groups["owner"].Value); foreach (Match x in Vat().Matches(b)) yield return L(f, "VAT Registered", x.Groups["v"].Value); foreach (Match x in Vrm().Matches(b)) yield return L(f, "Client registration", x.Groups["v"].Value); foreach (Match x in Make().Matches(b)) yield return L(f, "Client vehicle make", x.Groups["v"].Value); foreach (Match x in Model().Matches(b)) yield return L(f, "Client vehicle model", x.Groups["v"].Value); foreach (Match x in Category().Matches(b)) yield return L(f, "Vehicle Category", x.Groups["v"].Value); foreach (Match x in Location().Matches(b)) if (x.Groups["v"].Value.Trim(" .".ToCharArray()).Length > 0) yield return L(f, "Vehicle location", x.Groups["v"].Value); foreach (Match x in Repairer().Matches(b)) yield return L(f, "Repairer", x.Groups["v"].Value); }
    static IntakeContentFragment L(IntakeContentFragment f, string l, string v) => f with { Text = $"{l}: {Ws().Replace(v, " ").Trim()}" };
    [GeneratedRegex(@"(?im)^\s*Dear\s+Sirs\s*$", RegexOptions.CultureInvariant, 100)] private static partial Regex Dear();
    [GeneratedRegex(@"(?im)^\s*Auto\s+Logistic\s+Solutions\s+Ltd\s*$", RegexOptions.CultureInvariant, 100)] private static partial Regex Sign();
    [GeneratedRegex(@"(?im)^\s*Our\s+Reference\s*:[ \t]*(?<v>[^\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Ref();
    [GeneratedRegex(@"(?im)^\s*(?<v>\d{1,2}(?:st|nd|rd|th)?\s+[A-Za-z]+\s+\d{4})\s*$", RegexOptions.CultureInvariant, 100)] private static partial Regex Date();
    [GeneratedRegex(@"(?im)^\s*Accident\s+Date\s*:[ \t]*(?<v>[^\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Accident();
    [GeneratedRegex(@"(?ims)Accident\s+Circumstances\s*:[ \t]*(?<v>.+?)(?=\n\s*Client\s+Details)", RegexOptions.CultureInvariant, 100)] private static partial Regex Circ();
    [GeneratedRegex(@"(?ims)Client\s+Details.*?\n\s*Name\s*:[ \t]*(?<client>[^\t\r\n]+).*?\n\s*Address\s*:[ \t]*(?<address>[^\t\r\n]+).*?(?:\tName\s*:[ \t]*(?<owner>[^\t\r\n]+))?\s*\n.*?VAT\s+Registered", RegexOptions.CultureInvariant, 100)] private static partial Regex Party();
    [GeneratedRegex(@"(?im)^\s*Tel\s*:[^\r\n]*\tName\s*:[ \t]*(?<owner>[^\t\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Owner();
    [GeneratedRegex(@"(?im)^\s*VAT\s+Registered\s*:[ \t]*(?<v>yes|no)\b", RegexOptions.CultureInvariant, 100)] private static partial Regex Vat();
    [GeneratedRegex(@"(?im)^\s*Vehicle\s+Reg\s*:[ \t]*(?<v>[^\t\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Vrm();
    [GeneratedRegex(@"(?im)^\s*Vehicle\s+Make\s*:[ \t]*(?<v>[^\t\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Make();
    [GeneratedRegex(@"(?im)^\s*Vehicle\s+Model\s*:[ \t]*(?<v>[^\t\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Model();
    [GeneratedRegex(@"(?im)^\s*Vehicle\s+Category\s*:[ \t]*(?<v>[^\t\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Category();
    [GeneratedRegex(@"(?im)vehicle\s+is\s+currently[^\r\n]*?found\s+at[ \t]*(?<v>[^\r\n]+)", RegexOptions.CultureInvariant, 100)] private static partial Regex Location();
    [GeneratedRegex(@"(?im)^\s*(?<v>[^\r\n]+?)\s+of\s+[^\r\n]+$", RegexOptions.CultureInvariant, 100)] private static partial Regex Repairer();
    [GeneratedRegex(@"\s+", RegexOptions.CultureInvariant, 100)] private static partial Regex Ws();
#pragma warning restore CA1725
}
