// <auto-generated />
using System;
using CollisionSpike.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollisionSpike.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CollisionSpikeDbContext))]
    partial class CollisionSpikeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IntakeReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IntakeReceiptId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.QdosIntakeAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoundsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int?>("HeightPixels")
                        .HasColumnType("int");

                    b.Property<Guid>("IntakeReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("WidthPixels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntakeReceiptId", "ContentHash");

                    b.ToTable("QdosIntakeAssets", (string)null);
                });

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.QdosIntakeReceiptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalReceiptToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OcrCandidatesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("SourceLength")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceHash");

                    b.HasIndex("SourceChannel", "ExternalReceiptToken")
                        .IsUnique();

                    b.ToTable("QdosIntakeReceipts", (string)null);
                });

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.QdosTypedDraftEntity", b =>
                {
                    b.Property<Guid>("IntakeReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccidentCircumstances")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ClaimNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClaimantName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("DateOfIncident")
                        .HasColumnType("date");

                    b.Property<string>("InspectionAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("InstructionDate")
                        .HasColumnType("date");

                    b.Property<string>("PrincipalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleMake")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("VehicleMileage")
                        .HasColumnType("bigint");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleRegistration")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IntakeReceiptId");

                    b.ToTable("QdosTypedDrafts", (string)null);
                });

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.AuditEventEntity", b =>
                {
                    b.HasOne("CollisionSpike.Infrastructure.Persistence.QdosIntakeReceiptEntity", null)
                        .WithMany()
                        .HasForeignKey("IntakeReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.QdosIntakeAssetEntity", b =>
                {
                    b.HasOne("CollisionSpike.Infrastructure.Persistence.QdosIntakeReceiptEntity", "IntakeReceipt")
                        .WithMany("Assets")
                        .HasForeignKey("IntakeReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeReceipt");
                });

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.QdosTypedDraftEntity", b =>
                {
                    b.HasOne("CollisionSpike.Infrastructure.Persistence.QdosIntakeReceiptEntity", "IntakeReceipt")
                        .WithOne("TypedDraft")
                        .HasForeignKey("CollisionSpike.Infrastructure.Persistence.QdosTypedDraftEntity", "IntakeReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeReceipt");
                });

            modelBuilder.Entity("CollisionSpike.Infrastructure.Persistence.QdosIntakeReceiptEntity", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("TypedDraft");
                });
#pragma warning restore 612, 618
        }
    }
}
