// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class AiJobEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.AiJobEntity",
                typeof(AiJobEntity),
                baseEntityType,
                propertyCount: 36,
                unnamedIndexCount: 6,
                keyCount: 1);

            var jobId = runtimeEntityType.AddProperty(
                "JobId",
                typeof(Guid),
                propertyInfo: typeof(AiJobEntity).GetProperty("JobId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<JobId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            jobId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var closedAtUtc = runtimeEntityType.AddProperty(
                "ClosedAtUtc",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(AiJobEntity).GetProperty("ClosedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<ClosedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            closedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var closureReason = runtimeEntityType.AddProperty(
                "ClosureReason",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("ClosureReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<ClosureReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            closureReason.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdAtUtc = runtimeEntityType.AddProperty(
                "CreatedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(AiJobEntity).GetProperty("CreatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<CreatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            createdBy.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdByKind = runtimeEntityType.AddProperty(
                "CreatedByKind",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("CreatedByKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<CreatedByKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            createdByKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var draftReadyAtUtc = runtimeEntityType.AddProperty(
                "DraftReadyAtUtc",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(AiJobEntity).GetProperty("DraftReadyAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<DraftReadyAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            draftReadyAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var engineerValueAtSend = runtimeEntityType.AddProperty(
                "EngineerValueAtSend",
                typeof(decimal?),
                propertyInfo: typeof(AiJobEntity).GetProperty("EngineerValueAtSend", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<EngineerValueAtSend>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                precision: 18,
                scale: 2);
            engineerValueAtSend.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var expiresAtUtc = runtimeEntityType.AddProperty(
                "ExpiresAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(AiJobEntity).GetProperty("ExpiresAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<ExpiresAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            expiresAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var instruction = runtimeEntityType.AddProperty(
                "Instruction",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("Instruction", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<Instruction>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            instruction.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var kind = runtimeEntityType.AddProperty(
                "Kind",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("Kind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<Kind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            kind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var lastOperationKey = runtimeEntityType.AddProperty(
                "LastOperationKey",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("LastOperationKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<LastOperationKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            lastOperationKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var leaseExpiresAtUtc = runtimeEntityType.AddProperty(
                "LeaseExpiresAtUtc",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(AiJobEntity).GetProperty("LeaseExpiresAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<LeaseExpiresAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            leaseExpiresAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchCompletionHash = runtimeEntityType.AddProperty(
                "MarketResearchCompletionHash",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchCompletionHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchCompletionHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 64);
            marketResearchCompletionHash.AddAnnotation("Relational:IsFixedLength", true);
            marketResearchCompletionHash.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchDocumentOccurrenceId = runtimeEntityType.AddProperty(
                "MarketResearchDocumentOccurrenceId",
                typeof(Guid?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchDocumentOccurrenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchDocumentOccurrenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            marketResearchDocumentOccurrenceId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchDocumentVersionId = runtimeEntityType.AddProperty(
                "MarketResearchDocumentVersionId",
                typeof(Guid?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchDocumentVersionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchDocumentVersionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            marketResearchDocumentVersionId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchMileage = runtimeEntityType.AddProperty(
                "MarketResearchMileage",
                typeof(long?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchMileage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchMileage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            marketResearchMileage.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchRecordedDate = runtimeEntityType.AddProperty(
                "MarketResearchRecordedDate",
                typeof(DateOnly?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchRecordedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchRecordedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            marketResearchRecordedDate.AddAnnotation("Relational:ColumnType", "date");
            marketResearchRecordedDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchRecordedTime = runtimeEntityType.AddProperty(
                "MarketResearchRecordedTime",
                typeof(TimeOnly?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchRecordedTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchRecordedTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            marketResearchRecordedTime.AddAnnotation("Relational:ColumnType", "time");
            marketResearchRecordedTime.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchRetailValue = runtimeEntityType.AddProperty(
                "MarketResearchRetailValue",
                typeof(decimal?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchRetailValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchRetailValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                precision: 18,
                scale: 2);
            marketResearchRetailValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchTradeValue = runtimeEntityType.AddProperty(
                "MarketResearchTradeValue",
                typeof(decimal?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchTradeValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchTradeValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                precision: 18,
                scale: 2);
            marketResearchTradeValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var marketResearchValuationId = runtimeEntityType.AddProperty(
                "MarketResearchValuationId",
                typeof(Guid?),
                propertyInfo: typeof(AiJobEntity).GetProperty("MarketResearchValuationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<MarketResearchValuationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            marketResearchValuationId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var operationKey = runtimeEntityType.AddProperty(
                "OperationKey",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("OperationKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<OperationKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            operationKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var progressNote = runtimeEntityType.AddProperty(
                "ProgressNote",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("ProgressNote", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<ProgressNote>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            progressNote.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var requestHash = runtimeEntityType.AddProperty(
                "RequestHash",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("RequestHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<RequestHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            requestHash.AddAnnotation("Relational:IsFixedLength", true);
            requestHash.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resultKind = runtimeEntityType.AddProperty(
                "ResultKind",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("ResultKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<ResultKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);
            resultKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resultReference = runtimeEntityType.AddProperty(
                "ResultReference",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("ResultReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<ResultReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            resultReference.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resultText = runtimeEntityType.AddProperty(
                "ResultText",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("ResultText", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<ResultText>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 4000);
            resultText.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var state = runtimeEntityType.AddProperty(
                "State",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            state.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var subjectId = runtimeEntityType.AddProperty(
                "SubjectId",
                typeof(Guid?),
                propertyInfo: typeof(AiJobEntity).GetProperty("SubjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<SubjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            subjectId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var subjectKind = runtimeEntityType.AddProperty(
                "SubjectKind",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("SubjectKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<SubjectKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            subjectKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var subjectReference = runtimeEntityType.AddProperty(
                "SubjectReference",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("SubjectReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<SubjectReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            subjectReference.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var takenAtUtc = runtimeEntityType.AddProperty(
                "TakenAtUtc",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(AiJobEntity).GetProperty("TakenAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<TakenAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            takenAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var takenBy = runtimeEntityType.AddProperty(
                "TakenBy",
                typeof(string),
                propertyInfo: typeof(AiJobEntity).GetProperty("TakenBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<TakenBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            takenBy.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var targetPercentOfEngineerValue = runtimeEntityType.AddProperty(
                "TargetPercentOfEngineerValue",
                typeof(int?),
                propertyInfo: typeof(AiJobEntity).GetProperty("TargetPercentOfEngineerValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<TargetPercentOfEngineerValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            targetPercentOfEngineerValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(AiJobEntity).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AiJobEntity).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { jobId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { createdAtUtc });

            var index0 = runtimeEntityType.AddIndex(
                new[] { marketResearchDocumentOccurrenceId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { marketResearchValuationId });

            var index2 = runtimeEntityType.AddIndex(
                new[] { operationKey },
                unique: true);

            var index3 = runtimeEntityType.AddIndex(
                new[] { subjectId });

            var index4 = runtimeEntityType.AddIndex(
                new[] { state, leaseExpiresAtUtc });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AiJobs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
