// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class ApprovedInboxPoisonMessageEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.ApprovedInboxPoisonMessageEntity",
                typeof(ApprovedInboxPoisonMessageEntity),
                baseEntityType,
                propertyCount: 14,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var approvedMailboxId = runtimeEntityType.AddProperty(
                "ApprovedMailboxId",
                typeof(Guid),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("ApprovedMailboxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<ApprovedMailboxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            approvedMailboxId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var cursorAfterMessage = runtimeEntityType.AddProperty(
                "CursorAfterMessage",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("CursorAfterMessage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<CursorAfterMessage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            cursorAfterMessage.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var evidenceMarker = runtimeEntityType.AddProperty(
                "EvidenceMarker",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("EvidenceMarker", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<EvidenceMarker>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            evidenceMarker.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var failureCode = runtimeEntityType.AddProperty(
                "FailureCode",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("FailureCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<FailureCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            failureCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fileName = runtimeEntityType.AddProperty(
                "FileName",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("FileName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<FileName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            fileName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var immutableMessageId = runtimeEntityType.AddProperty(
                "ImmutableMessageId",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("ImmutableMessageId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<ImmutableMessageId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            immutableMessageId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var occurrenceKey = runtimeEntityType.AddProperty(
                "OccurrenceKey",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("OccurrenceKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<OccurrenceKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            occurrenceKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var originalSourceHash = runtimeEntityType.AddProperty(
                "OriginalSourceHash",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("OriginalSourceHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<OriginalSourceHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 64);
            originalSourceHash.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var quarantinedAtUtc = runtimeEntityType.AddProperty(
                "QuarantinedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("QuarantinedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<QuarantinedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            quarantinedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var receivedAtUtc = runtimeEntityType.AddProperty(
                "ReceivedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("ReceivedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<ReceivedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            receivedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceHash = runtimeEntityType.AddProperty(
                "SourceHash",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("SourceHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<SourceHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 64);
            sourceHash.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceLength = runtimeEntityType.AddProperty(
                "SourceLength",
                typeof(long?),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("SourceLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<SourceLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sourceLength.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var storageKey = runtimeEntityType.AddProperty(
                "StorageKey",
                typeof(string),
                propertyInfo: typeof(ApprovedInboxPoisonMessageEntity).GetProperty("StorageKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApprovedInboxPoisonMessageEntity).GetField("<StorageKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            storageKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { approvedMailboxId, occurrenceKey },
                unique: true);

            var index0 = runtimeEntityType.AddIndex(
                new[] { quarantinedAtUtc, id });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ApprovedMailboxId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("ApprovedMailboxId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ApprovedInboxPoisonMessages");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
