// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class InstructionDraftEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.InstructionDraftEntity",
                typeof(InstructionDraftEntity),
                baseEntityType,
                propertyCount: 20,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var intakeReceiptId = runtimeEntityType.AddProperty(
                "IntakeReceiptId",
                typeof(Guid),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("IntakeReceiptId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<IntakeReceiptId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            intakeReceiptId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var accidentCircumstances = runtimeEntityType.AddProperty(
                "AccidentCircumstances",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("AccidentCircumstances", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<AccidentCircumstances>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            accidentCircumstances.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var claimNumber = runtimeEntityType.AddProperty(
                "ClaimNumber",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("ClaimNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<ClaimNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            claimNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var claimantAddress = runtimeEntityType.AddProperty(
                "ClaimantAddress",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("ClaimantAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<ClaimantAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000);
            claimantAddress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var claimantContactNumber = runtimeEntityType.AddProperty(
                "ClaimantContactNumber",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("ClaimantContactNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<ClaimantContactNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            claimantContactNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var claimantName = runtimeEntityType.AddProperty(
                "ClaimantName",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("ClaimantName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<ClaimantName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 300);
            claimantName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dateOfIncident = runtimeEntityType.AddProperty(
                "DateOfIncident",
                typeof(DateOnly?),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("DateOfIncident", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<DateOfIncident>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            dateOfIncident.AddAnnotation("Relational:ColumnType", "date");
            dateOfIncident.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fileHandlerEmailAddress = runtimeEntityType.AddProperty(
                "FileHandlerEmailAddress",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("FileHandlerEmailAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<FileHandlerEmailAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 320);
            fileHandlerEmailAddress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fileHandlerName = runtimeEntityType.AddProperty(
                "FileHandlerName",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("FileHandlerName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<FileHandlerName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 300);
            fileHandlerName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fileHandlerPhoneNumber = runtimeEntityType.AddProperty(
                "FileHandlerPhoneNumber",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("FileHandlerPhoneNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<FileHandlerPhoneNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            fileHandlerPhoneNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var inspectionAddress = runtimeEntityType.AddProperty(
                "InspectionAddress",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("InspectionAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<InspectionAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000);
            inspectionAddress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var inspectionDate = runtimeEntityType.AddProperty(
                "InspectionDate",
                typeof(DateOnly?),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("InspectionDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<InspectionDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            inspectionDate.AddAnnotation("Relational:ColumnType", "date");
            inspectionDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var notes = runtimeEntityType.AddProperty(
                "Notes",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            notes.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var suggestedPrincipalCode = runtimeEntityType.AddProperty(
                "SuggestedPrincipalCode",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("SuggestedPrincipalCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<SuggestedPrincipalCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 20);
            suggestedPrincipalCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vatStatus = runtimeEntityType.AddProperty(
                "VatStatus",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("VatStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<VatStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            vatStatus.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleMake = runtimeEntityType.AddProperty(
                "VehicleMake",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("VehicleMake", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<VehicleMake>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            vehicleMake.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleMileage = runtimeEntityType.AddProperty(
                "VehicleMileage",
                typeof(long?),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("VehicleMileage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<VehicleMileage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vehicleMileage.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleMileageUnit = runtimeEntityType.AddProperty(
                "VehicleMileageUnit",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("VehicleMileageUnit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<VehicleMileageUnit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);
            vehicleMileageUnit.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleModel = runtimeEntityType.AddProperty(
                "VehicleModel",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("VehicleModel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<VehicleModel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            vehicleModel.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleRegistration = runtimeEntityType.AddProperty(
                "VehicleRegistration",
                typeof(string),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("VehicleRegistration", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<VehicleRegistration>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 20);
            vehicleRegistration.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { intakeReceiptId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IntakeReceiptId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var intakeReceipt = declaringEntityType.AddNavigation("IntakeReceipt",
                runtimeForeignKey,
                onDependent: true,
                typeof(IntakeReceiptEntity),
                propertyInfo: typeof(InstructionDraftEntity).GetProperty("IntakeReceipt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InstructionDraftEntity).GetField("<IntakeReceipt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var instructionDraft = principalEntityType.AddNavigation("InstructionDraft",
                runtimeForeignKey,
                onDependent: false,
                typeof(InstructionDraftEntity),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("InstructionDraft", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<InstructionDraft>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "InstructionDrafts");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
