// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class IntakeReceiptEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.IntakeReceiptEntity",
                typeof(IntakeReceiptEntity),
                baseEntityType,
                propertyCount: 22,
                navigationCount: 7,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var decision = runtimeEntityType.AddProperty(
                "Decision",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("Decision", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<Decision>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            decision.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var decisionReason = runtimeEntityType.AddProperty(
                "DecisionReason",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("DecisionReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<DecisionReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            decisionReason.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var declaredCaseId = runtimeEntityType.AddProperty(
                "DeclaredCaseId",
                typeof(Guid?),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("DeclaredCaseId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<DeclaredCaseId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            declaredCaseId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var evidenceJson = runtimeEntityType.AddProperty(
                "EvidenceJson",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("EvidenceJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<EvidenceJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            evidenceJson.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var externalReceiptToken = runtimeEntityType.AddProperty(
                "ExternalReceiptToken",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("ExternalReceiptToken", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<ExternalReceiptToken>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            externalReceiptToken.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var extractionPolicyKey = runtimeEntityType.AddProperty(
                "ExtractionPolicyKey",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("ExtractionPolicyKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<ExtractionPolicyKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            extractionPolicyKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var extractionPolicyVersion = runtimeEntityType.AddProperty(
                "ExtractionPolicyVersion",
                typeof(int?),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("ExtractionPolicyVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<ExtractionPolicyVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            extractionPolicyVersion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var failureCode = runtimeEntityType.AddProperty(
                "FailureCode",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("FailureCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<FailureCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            failureCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var failureReason = runtimeEntityType.AddProperty(
                "FailureReason",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("FailureReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<FailureReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            failureReason.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fieldsJson = runtimeEntityType.AddProperty(
                "FieldsJson",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("FieldsJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<FieldsJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            fieldsJson.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mediaType = runtimeEntityType.AddProperty(
                "MediaType",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("MediaType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<MediaType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            mediaType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ocrCandidatesJson = runtimeEntityType.AddProperty(
                "OcrCandidatesJson",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("OcrCandidatesJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<OcrCandidatesJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            ocrCandidatesJson.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var processedAtUtc = runtimeEntityType.AddProperty(
                "ProcessedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("ProcessedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<ProcessedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            processedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var receivedAtUtc = runtimeEntityType.AddProperty(
                "ReceivedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("ReceivedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<ReceivedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            receivedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceChannel = runtimeEntityType.AddProperty(
                "SourceChannel",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("SourceChannel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<SourceChannel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            sourceChannel.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceFileName = runtimeEntityType.AddProperty(
                "SourceFileName",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("SourceFileName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<SourceFileName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 260);
            sourceFileName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceHash = runtimeEntityType.AddProperty(
                "SourceHash",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("SourceHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<SourceHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            sourceHash.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceLength = runtimeEntityType.AddProperty(
                "SourceLength",
                typeof(long),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("SourceLength", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<SourceLength>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            sourceLength.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceReaderKey = runtimeEntityType.AddProperty(
                "SourceReaderKey",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("SourceReaderKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<SourceReaderKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            sourceReaderKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceReaderVersion = runtimeEntityType.AddProperty(
                "SourceReaderVersion",
                typeof(string),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("SourceReaderVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<SourceReaderVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            sourceReaderVersion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(IntakeReceiptEntity).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntakeReceiptEntity).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { declaredCaseId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { sourceHash });

            var index1 = runtimeEntityType.AddIndex(
                new[] { sourceChannel, externalReceiptToken },
                unique: true);

            var index2 = runtimeEntityType.AddIndex(
                new[] { sourceChannel, receivedAtUtc });

            var index3 = runtimeEntityType.AddIndex(
                new[] { sourceChannel, processedAtUtc, id });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "IntakeReceipts");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
