// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class PrincipalDomainPackageEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.PrincipalDomainPackageEntity",
                typeof(PrincipalDomainPackageEntity),
                baseEntityType,
                propertyCount: 7,
                navigationCount: 1,
                keyCount: 1);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(string),
                propertyInfo: typeof(PrincipalDomainPackageEntity).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrincipalDomainPackageEntity).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 64);
            version.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var packageSha256 = runtimeEntityType.AddProperty(
                "PackageSha256",
                typeof(string),
                propertyInfo: typeof(PrincipalDomainPackageEntity).GetProperty("PackageSha256", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrincipalDomainPackageEntity).GetField("<PackageSha256>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            packageSha256.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var schemaVersion = runtimeEntityType.AddProperty(
                "SchemaVersion",
                typeof(int),
                propertyInfo: typeof(PrincipalDomainPackageEntity).GetProperty("SchemaVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrincipalDomainPackageEntity).GetField("<SchemaVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            schemaVersion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceContentSha256 = runtimeEntityType.AddProperty(
                "SourceContentSha256",
                typeof(string),
                propertyInfo: typeof(PrincipalDomainPackageEntity).GetProperty("SourceContentSha256", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrincipalDomainPackageEntity).GetField("<SourceContentSha256>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            sourceContentSha256.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourcePath = runtimeEntityType.AddProperty(
                "SourcePath",
                typeof(string),
                propertyInfo: typeof(PrincipalDomainPackageEntity).GetProperty("SourcePath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrincipalDomainPackageEntity).GetField("<SourcePath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            sourcePath.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceRowCount = runtimeEntityType.AddProperty(
                "SourceRowCount",
                typeof(int),
                propertyInfo: typeof(PrincipalDomainPackageEntity).GetProperty("SourceRowCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrincipalDomainPackageEntity).GetField("<SourceRowCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            sourceRowCount.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceSheet = runtimeEntityType.AddProperty(
                "SourceSheet",
                typeof(string),
                propertyInfo: typeof(PrincipalDomainPackageEntity).GetProperty("SourceSheet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PrincipalDomainPackageEntity).GetField("<SourceSheet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 31);
            sourceSheet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { version });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PrincipalDomainPackages");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
