// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class TriageResponseEvidenceLinkEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.TriageResponseEvidenceLinkEntity",
                typeof(TriageResponseEvidenceLinkEntity),
                baseEntityType,
                propertyCount: 6,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 3,
                keyCount: 1);

            var triageCaseId = runtimeEntityType.AddProperty(
                "TriageCaseId",
                typeof(Guid),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("TriageCaseId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<TriageCaseId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            triageCaseId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sentEvidenceId = runtimeEntityType.AddProperty(
                "SentEvidenceId",
                typeof(Guid),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("SentEvidenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<SentEvidenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            sentEvidenceId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var actor = runtimeEntityType.AddProperty(
                "Actor",
                typeof(string),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("Actor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<Actor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            actor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var linkedAtUtc = runtimeEntityType.AddProperty(
                "LinkedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("LinkedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<LinkedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            linkedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var operationKey = runtimeEntityType.AddProperty(
                "OperationKey",
                typeof(string),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("OperationKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<OperationKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            operationKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reason = runtimeEntityType.AddProperty(
                "Reason",
                typeof(string),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("Reason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<Reason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            reason.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { triageCaseId, sentEvidenceId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { operationKey },
                unique: true);

            var index0 = runtimeEntityType.AddIndex(
                new[] { sentEvidenceId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { triageCaseId },
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SentEvidenceId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var sentEvidence = declaringEntityType.AddNavigation("SentEvidence",
                runtimeForeignKey,
                onDependent: true,
                typeof(SentEmailEvidenceEntity),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("SentEvidence", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<SentEvidence>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var triageLinks = principalEntityType.AddNavigation("TriageLinks",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<TriageResponseEvidenceLinkEntity>),
                propertyInfo: typeof(SentEmailEvidenceEntity).GetProperty("TriageLinks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SentEmailEvidenceEntity).GetField("<TriageLinks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TriageCaseId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("CaseId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var triage = declaringEntityType.AddNavigation("Triage",
                runtimeForeignKey,
                onDependent: true,
                typeof(TriageEntity),
                propertyInfo: typeof(TriageResponseEvidenceLinkEntity).GetProperty("Triage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageResponseEvidenceLinkEntity).GetField("<Triage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var responseEvidenceLinks = principalEntityType.AddNavigation("ResponseEvidenceLinks",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<TriageResponseEvidenceLinkEntity>),
                propertyInfo: typeof(TriageEntity).GetProperty("ResponseEvidenceLinks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TriageEntity).GetField("<ResponseEvidenceLinks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "TriageResponseEvidenceLinks");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
