// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class UnidentifiedItemEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.UnidentifiedItemEntity",
                typeof(UnidentifiedItemEntity),
                baseEntityType,
                propertyCount: 27,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdAtUtc = runtimeEntityType.AddProperty(
                "CreatedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("CreatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<CreatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdByActorKind = runtimeEntityType.AddProperty(
                "CreatedByActorKind",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("CreatedByActorKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<CreatedByActorKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            createdByActorKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdByActorRolesJson = runtimeEntityType.AddProperty(
                "CreatedByActorRolesJson",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("CreatedByActorRolesJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<CreatedByActorRolesJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            createdByActorRolesJson.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdByActorSubjectId = runtimeEntityType.AddProperty(
                "CreatedByActorSubjectId",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("CreatedByActorSubjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<CreatedByActorSubjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            createdByActorSubjectId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fileKind = runtimeEntityType.AddProperty(
                "FileKind",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("FileKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<FileKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            fileKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var originId = runtimeEntityType.AddProperty(
                "OriginId",
                typeof(Guid),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("OriginId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<OriginId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            originId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var originKind = runtimeEntityType.AddProperty(
                "OriginKind",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("OriginKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<OriginKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            originKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reasonCode = runtimeEntityType.AddProperty(
                "ReasonCode",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ReasonCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ReasonCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 80);
            reasonCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reconciledAssociationVersion = runtimeEntityType.AddProperty(
                "ReconciledAssociationVersion",
                typeof(long?),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ReconciledAssociationVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ReconciledAssociationVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reconciledAssociationVersion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reference = runtimeEntityType.AddProperty(
                "Reference",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("Reference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<Reference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            reference.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var registrationFingerprint = runtimeEntityType.AddProperty(
                "RegistrationFingerprint",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("RegistrationFingerprint", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<RegistrationFingerprint>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            registrationFingerprint.AddAnnotation("Relational:IsFixedLength", true);
            registrationFingerprint.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var registrationOperationKey = runtimeEntityType.AddProperty(
                "RegistrationOperationKey",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("RegistrationOperationKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<RegistrationOperationKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            registrationOperationKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolutionReason = runtimeEntityType.AddProperty(
                "ResolutionReason",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolutionReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolutionReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            resolutionReason.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolutionTargetId = runtimeEntityType.AddProperty(
                "ResolutionTargetId",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolutionTargetId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolutionTargetId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            resolutionTargetId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolutionTargetKind = runtimeEntityType.AddProperty(
                "ResolutionTargetKind",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolutionTargetKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolutionTargetKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);
            resolutionTargetKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolutionTargetReference = runtimeEntityType.AddProperty(
                "ResolutionTargetReference",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolutionTargetReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolutionTargetReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            resolutionTargetReference.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolvedAtUtc = runtimeEntityType.AddProperty(
                "ResolvedAtUtc",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolvedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolvedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            resolvedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolvedByActorKind = runtimeEntityType.AddProperty(
                "ResolvedByActorKind",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolvedByActorKind", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolvedByActorKind>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);
            resolvedByActorKind.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolvedByActorRolesJson = runtimeEntityType.AddProperty(
                "ResolvedByActorRolesJson",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolvedByActorRolesJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolvedByActorRolesJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            resolvedByActorRolesJson.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resolvedByActorSubjectId = runtimeEntityType.AddProperty(
                "ResolvedByActorSubjectId",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("ResolvedByActorSubjectId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<ResolvedByActorSubjectId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            resolvedByActorSubjectId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var safeDetail = runtimeEntityType.AddProperty(
                "SafeDetail",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("SafeDetail", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<SafeDetail>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 1000);
            safeDetail.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sequence = runtimeEntityType.AddProperty(
                "Sequence",
                typeof(long),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("Sequence", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<Sequence>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            sequence.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceAssetId = runtimeEntityType.AddProperty(
                "SourceAssetId",
                typeof(Guid?),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("SourceAssetId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<SourceAssetId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sourceAssetId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceMessageId = runtimeEntityType.AddProperty(
                "SourceMessageId",
                typeof(Guid?),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("SourceMessageId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<SourceMessageId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sourceMessageId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var state = runtimeEntityType.AddProperty(
                "State",
                typeof(string),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            state.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var version = runtimeEntityType.AddProperty(
                "Version",
                typeof(long),
                propertyInfo: typeof(UnidentifiedItemEntity).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UnidentifiedItemEntity).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            version.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { reference },
                unique: true);

            var index0 = runtimeEntityType.AddIndex(
                new[] { registrationOperationKey },
                unique: true);

            var index1 = runtimeEntityType.AddIndex(
                new[] { sequence },
                unique: true);

            var index2 = runtimeEntityType.AddIndex(
                new[] { originKind, originId },
                unique: true);

            var index3 = runtimeEntityType.AddIndex(
                new[] { state, createdAtUtc, sequence });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "UnidentifiedItems");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
