// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pegasus.Infrastructure.Persistence.CompiledModel
{
    [EntityFrameworkInternal]
    public partial class VehicleLookupObservationEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Pegasus.Infrastructure.Persistence.VehicleLookupObservationEntity",
                typeof(VehicleLookupObservationEntity),
                baseEntityType,
                propertyCount: 32,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var attemptNumber = runtimeEntityType.AddProperty(
                "AttemptNumber",
                typeof(int),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("AttemptNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<AttemptNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attemptNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var colour = runtimeEntityType.AddProperty(
                "Colour",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Colour", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Colour>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            colour.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var effectiveAtUtc = runtimeEntityType.AddProperty(
                "EffectiveAtUtc",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("EffectiveAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<EffectiveAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            effectiveAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var engineCapacityCc = runtimeEntityType.AddProperty(
                "EngineCapacityCc",
                typeof(int?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("EngineCapacityCc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<EngineCapacityCc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            engineCapacityCc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var failureCode = runtimeEntityType.AddProperty(
                "FailureCode",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("FailureCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<FailureCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            failureCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var failureRetryAfterTicks = runtimeEntityType.AddProperty(
                "FailureRetryAfterTicks",
                typeof(long?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("FailureRetryAfterTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<FailureRetryAfterTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            failureRetryAfterTicks.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var failureRetryable = runtimeEntityType.AddProperty(
                "FailureRetryable",
                typeof(bool?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("FailureRetryable", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<FailureRetryable>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            failureRetryable.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fuelType = runtimeEntityType.AddProperty(
                "FuelType",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("FuelType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<FuelType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            fuelType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var make = runtimeEntityType.AddProperty(
                "Make",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Make", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Make>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            make.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var manufactureYear = runtimeEntityType.AddProperty(
                "ManufactureYear",
                typeof(int?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("ManufactureYear", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<ManufactureYear>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            manufactureYear.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mileageMethodKey = runtimeEntityType.AddProperty(
                "MileageMethodKey",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("MileageMethodKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<MileageMethodKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            mileageMethodKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mileageMethodVersion = runtimeEntityType.AddProperty(
                "MileageMethodVersion",
                typeof(int?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("MileageMethodVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<MileageMethodVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            mileageMethodVersion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mileageObservedOn = runtimeEntityType.AddProperty(
                "MileageObservedOn",
                typeof(DateOnly?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("MileageObservedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<MileageObservedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            mileageObservedOn.AddAnnotation("Relational:ColumnType", "date");
            mileageObservedOn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mileageSupportingObservationCount = runtimeEntityType.AddProperty(
                "MileageSupportingObservationCount",
                typeof(int?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("MileageSupportingObservationCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<MileageSupportingObservationCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            mileageSupportingObservationCount.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mileageUnit = runtimeEntityType.AddProperty(
                "MileageUnit",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("MileageUnit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<MileageUnit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 40);
            mileageUnit.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mileageValue = runtimeEntityType.AddProperty(
                "MileageValue",
                typeof(long?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("MileageValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<MileageValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            mileageValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var model0 = runtimeEntityType.AddProperty(
                "Model",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Model", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Model>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            model0.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var motTestsJson = runtimeEntityType.AddProperty(
                "MotTestsJson",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("MotTestsJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<MotTestsJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            motTestsJson.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var outcome = runtimeEntityType.AddProperty(
                "Outcome",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Outcome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Outcome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 40);
            outcome.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var provider = runtimeEntityType.AddProperty(
                "Provider",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Provider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Provider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            provider.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var providerVersion = runtimeEntityType.AddProperty(
                "ProviderVersion",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("ProviderVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<ProviderVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            providerVersion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var recordedAtUtc = runtimeEntityType.AddProperty(
                "RecordedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("RecordedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<RecordedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            recordedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var registration = runtimeEntityType.AddProperty(
                "Registration",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Registration", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Registration>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            registration.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var responseIdentity = runtimeEntityType.AddProperty(
                "ResponseIdentity",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("ResponseIdentity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<ResponseIdentity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            responseIdentity.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var retrievedAtUtc = runtimeEntityType.AddProperty(
                "RetrievedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("RetrievedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<RetrievedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            retrievedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var revenueWeightKg = runtimeEntityType.AddProperty(
                "RevenueWeightKg",
                typeof(int?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("RevenueWeightKg", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<RevenueWeightKg>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            revenueWeightKg.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sourceObservedAtUtc = runtimeEntityType.AddProperty(
                "SourceObservedAtUtc",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("SourceObservedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<SourceObservedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sourceObservedAtUtc.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var taxDueDate = runtimeEntityType.AddProperty(
                "TaxDueDate",
                typeof(DateOnly?),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("TaxDueDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<TaxDueDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            taxDueDate.AddAnnotation("Relational:ColumnType", "date");
            taxDueDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var typeApproval = runtimeEntityType.AddProperty(
                "TypeApproval",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("TypeApproval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<TypeApproval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            typeApproval.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var wheelplan = runtimeEntityType.AddProperty(
                "Wheelplan",
                typeof(string),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Wheelplan", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Wheelplan>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            wheelplan.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var workItemId = runtimeEntityType.AddProperty(
                "WorkItemId",
                typeof(Guid),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("WorkItemId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<WorkItemId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            workItemId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { workItemId, attemptNumber },
                unique: true);

            var index0 = runtimeEntityType.AddIndex(
                new[] { provider, providerVersion, responseIdentity });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("WorkItemId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("WorkItemId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var request = declaringEntityType.AddNavigation("Request",
                runtimeForeignKey,
                onDependent: true,
                typeof(VehicleLookupRequestEntity),
                propertyInfo: typeof(VehicleLookupObservationEntity).GetProperty("Request", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupObservationEntity).GetField("<Request>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var observations = principalEntityType.AddNavigation("Observations",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<VehicleLookupObservationEntity>),
                propertyInfo: typeof(VehicleLookupRequestEntity).GetProperty("Observations", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(VehicleLookupRequestEntity).GetField("<Observations>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "VehicleLookupObservations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
